In [1]:

# RGIA Airport Operations & Traffic Analytics
# Notebook 01: Data Acquisition & Audit

PROJECT_NAME = "RGIA Airport Operations & Traffic Analytics"
PRIMARY_SOURCE = "Airports Authority of India (AAI)"
SOURCE_PAGE = "https://www.aai.aero/en/business-opportunities/aai-traffic-news"

print(PROJECT_NAME)
print(f"Primary Source: {PRIMARY_SOURCE}")
print(f"Source Page: {SOURCE_PAGE}")

RGIA Airport Operations & Traffic Analytics
Primary Source: Airports Authority of India (AAI)
Source Page: https://www.aai.aero/en/business-opportunities/aai-traffic-news

In [2]:
!pip -q install requests beautifulsoup4 pandas lxml openpyxl pdfplumber

import requests
import pandas as pd
import numpy as np
import re
import os
from bs4 import BeautifulSoup
from io import BytesIO

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries loaded successfully.")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 2.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 63.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 113.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 102.4 MB/s eta 0:00:00
Libraries loaded successfully.

In [4]:
AAI_URL = "https://www.aai.aero/en/business-opportunities/aai-traffic-news"

response = requests.get(
    AAI_URL,
    headers={"User-Agent": "Mozilla/5.0"},
    timeout=30
)

print("Status code:", response.status_code)
print("Page size:", len(response.content), "bytes")

Status code: 200
Page size: 930164 bytes

In [5]:
soup = BeautifulSoup(response.content, "html.parser")

links = soup.find_all("a")

aai_links = []

for link in links:
    href = link.get("href")
    text = link.get_text(" ", strip=True)

    if href and (
        "Annexure" in text
        or "Traffic News" in text
        or "Passengers" in text
        or "Freight" in text
        or "Aircraft Movement" in text
    ):
        aai_links.append({
            "text": text,
            "url": href
        })

aai_links[:20]

[{'text': 'Traffic News',
  'url': '/en/business-opportunities/aai-traffic-news'},
 {'text': 'Traffic News',
  'url': '/en/business-opportunities/aai-traffic-news'},
 {'text': 'Traffic News Summary',
  'url': 'https://www.aai.aero/sites/default/files/traffic-news/TRAug2k26.pdf'},
 {'text': 'Traffic News Summary',
  'url': '/en/node/747348?width=700px&height=500px&inline=true#colorbox-inline-106330072'},
 {'text': 'Traffic News Summary',
  'url': 'https://www.aai.aero/sites/default/files/traffic-news/TRAug2k26.pdf'},
 {'text': 'Annexure-I-Airport Category wise Traffic Summary',
  'url': 'https://www.aai.aero/sites/default/files/traffic-news/Aug2k26Annex1.pdf'},
 {'text': 'Annexure-I-Airport Category wise Traffic Summary',
  'url': '/en/node/747349?width=700px&height=500px&inline=true#colorbox-inline-953443811'},
 {'text': 'Annexure-I-Airport Category wise Traffic Summary',
  'url': 'https://www.aai.aero/sites/default/files/traffic-news/Aug2k26Annex1.pdf'},
 {'text': 'Annexure-II-Aircraft Movement',
  'url': 'https://www.aai.aero/sites/default/files/traffic-news/Aug2k26Annex2.pdf'},
 {'text': 'Annexure-II-Aircraft Movement',
  'url': '/en/node/747350?width=700px&height=500px&inline=true#colorbox-inline-1713213948'},
 {'text': 'Annexure-II-Aircraft Movement',
  'url': 'https://www.aai.aero/sites/default/files/traffic-news/Aug2k26Annex2.pdf'},
 {'text': 'Annexure-III-Passengers',
  'url': 'https://www.aai.aero/sites/default/files/traffic-news/Aug2k26Annex3.pdf'},
 {'text': 'Annexure-III-Passengers',
  'url': '/en/node/747351?width=700px&height=500px&inline=true#colorbox-inline-588258258'},
 {'text': 'Annexure-III-Passengers',
  'url': 'https://www.aai.aero/sites/default/files/traffic-news/Aug2k26Annex3.pdf'},
 {'text': 'Annexure-IV-Freight',
  'url': 'https://www.aai.aero/sites/default/files/traffic-news/Aug2k26Annex_4.pdf'},
 {'text': 'Annexure-IV-Freight',
  'url': '/en/node/747352?width=700px&height=500px&inline=true#colorbox-inline-2070188690'},
 {'text': 'Annexure-IV-Freight',
  'url': 'https://www.aai.aero/sites/default/files/traffic-news/Aug2k26Annex_4.pdf'},
 {'text': 'Annexure-V-Region Wise Trends and Share in Air Traffic',
  'url': 'https://www.aai.aero/sites/default/files/traffic-news/Aug2k26Annex5.pdf'},
 {'text': 'Annexure-V-Region Wise Trends and Share in Air Traffic',
  'url': '/en/node/747353?width=700px&height=500px&inline=true#colorbox-inline-993812459'},
 {'text': 'Annexure-V-Region Wise Trends and Share in Air Traffic',
  'url': 'https://www.aai.aero/sites/default/files/traffic-news/Aug2k26Annex5.pdf'}]

In [7]:

#August 2026 Passenger Report

PASSENGER_URL = (
    "https://www.aai.aero/sites/default/files/"
    "traffic-news/Aug2k26Annex3.pdf"
)

pdf_response = requests.get(
    PASSENGER_URL,
    headers={"User-Agent": "Mozilla/5.0"},
    timeout=30
)

print("Status code:", pdf_response.status_code)
print("File size:", round(len(pdf_response.content) / 1024, 2), "KB")
print("Content type:", pdf_response.headers.get("Content-Type"))

Status code: 200
File size: 488.7 KB
Content type: application/pdf

In [8]:
import pdfplumber

with pdfplumber.open(BytesIO(pdf_response.content)) as pdf:

    print("Number of pages:", len(pdf.pages))

    for i, page in enumerate(pdf.pages[:3]):
        text = page.extract_text()

        print(f"\n{'='*70}")
        print(f"PAGE {i + 1}")
        print(f"{'='*70}")

        if text:
            print(text[:5000])
        else:
            print("No text extracted.")

Number of pages: 7

======================================================================
PAGE 1
======================================================================
अनुलग्नक-III क ANNEXURE-III A
अंर्िरतष्ट्रीय यरत्री International Passengers
यरत्री (संख्यर में ) PASSENGERS (IN NOS.)
मरह के लिए For The Month अवलि के लिए For The Period
अगस्त अगस्त अप्रैि से अगस्त
क्र.सं % %
एयिपोर्त Airport August August April To August
S.NO
परिवर्तन परिवर्तन
2026 2025 2026-2027 2025-2026
Change Change
अंर्िरतष्ट्रीय एयिपोर्तस INTERNATIONAL AIRPORTS
1 अमृतसर AMRITSAR 65197 80663 -19.2% 298064 400206 -25.5%
2 अयोध्या AYODHYA 0 0 - 0 0 -
3 भुवनेश्वर BHUBANESWAR 3 10384 - 35207 46984 -25.1%
4 चेन्नई CHENNAI 488949 527736 -7.3% 2414765 2621778 -7.9%
5 कोयंबत्तूर COIMBATORE 22722 28990 -21.6% 99276 136597 -27.3%
6 गोवा GOA (DABOLIM) 6372 14822 -57.0% 24647 66237 -62.8%
7 इंफाल IMPHAL 0 0 - 0 0 -
8 कोलकाता KOLKATA 158624 172088 -7.8% 930440 925467 0.5%
9 कु शीनगर KUSHINAGAR 0 0 - 0 0 -
10 कोझिकोड KOZHIKODE 260932 285875 -8.7% 1045930 1333715 -21.6%
11 मदुरै MADURAI 9677 18258 -47.0% 31811 84446 -62.3%
12 पोर्ट ब्लेयर PORT BLAIR 0 0 - 0 1017 -
13 राजकोर् (हीरासर) RAJKOT (HIRASAR) 0 0 - 187 0 -
14 श्रीनगर SRINAGAR 0 0 - 3859 5120 -24.6%
15 सूरत SURAT 7021 15442 -54.5% 17406 82321 -78.9%
16 झतरुझचरापल्ली TIRUCHIRAPPALLI 106406 120413 -11.6% 482993 603659 -20.0%
17 झतरुपझत TIRUPATI 1 0 - 63 1 -
18 वाराणसी VARANASI 10197 9944 2.5% 42312 53378 -20.7%
19 झवजयवाडा VIJAYAWADA 5114 2441 - 19727 11055 78.4%
योग Total 1141215 1287056 -11.3% 5446687 6371981 -14.5%
पीपीपी अंर्िरतष्ट्रीय एयिपोर्तस PPP INTERNATIONAL
1 अहमदाबाद AHMEDABAD 159532 190583 -16.3% 804380 1004711 -19.9%
2 गुवाहार्ी GUWAHATI 4435 4866 -8.9% 25578 27604 -7.3%
3 जयपुर JAIPUR 36063 47467 -24.0% 155738 254191 -38.7%
4 लखनऊ LUCKNOW 85960 97661 -12.0% 419227 478705 -12.4%
5 मंगलुरु MANGALURU 72794 72849 -0.1% 278588 316925 -12.1%
6 झतरुवनंतपुरम THIRUVANANTHAPURAM 222823 246859 -9.7% 986570 1109774 -11.1%
योग Total 581607 660285 -11.9% 2670081 3191910 -16.3%
संयुक्त उिम एयिपोर्तस JV INTERNATIONAL AIRPORTS
1 बेंगलुरु BENGALURU (BIAL) 616381 581038 6.1% 2900539 2900924 0.0%
2 झदल्ली (यूर्ी) DELHI (DIAL) 1694347 1665392 1.7% 8639274 8550344 1.0%
3 हैदराबाद HYDERABAD (GHIAL) 452164 464341 -2.6% 2117531 2261073 -6.3%
4 कन्नूर (झकयाल) KANNUR (KIAL) 86444 105696 -18.2% 274317 496709 -44.8%
5 कोच्चि KOCHI 490846 499661 -1.8% 2058023 2361053 -12.8%
6 मुंबई MUMBAI (MIAL) 1266182 1327047 -4.6% 6236846 6567771 -5.0%
7 नागपुर NAGPUR 6797 9018 -24.6% 27359 46342 -41.0%
योग Total 4613161 4652193 -0.8% 22253889 23184216 -4.0%
िरज्य सिकरि / लनजी अंर्िरतष्ट्रीय ST GOVT/PVT INTERNATIONAL
1 गोवा (एमओपीए) GOA (MOPA) 15240 19430 -21.6% 71787 112110 -36.0%
2 नवी मुंबई NAVI MUMBAI (NMIAL) 2554 0 - 4010 0 -
3 नोएडा (झनयाल) NOIDA (NIAL) 0 0 - 0 0 -
4 झशरडी SHIRDI 0 0 - 0 0 -
5 झवशाखापत्तनम VISAKHAPATNAM (GVIAL) 7120 9248 -23.0% 25411 41532 -38.8%
योग Total 24914 28678 -13.1% 101208 153642 -34.1%
सीमर शुल्क एयिपोर्तस CUSTOM AIRPORTS
1 अगरतला AGARTALA 0 0 - 0 0 -
2 औरंगाबाद AURANGABAD 0 0 - 0 0 -
3 बागडोगरा BAGDOGRA 1255 1877 -33.1% 7957 11452 -30.5%
4 भोपाल BHOPAL 8 0 - 15 576 -97.4%
5 चंडीगढ़ (यूर्ी) CHANDIGARH 15220 14221 7.0% 31945 73252 -56.4%
6 गया GAYA 0 0 - 2377 3771 -37.0%
7 इंदौर INDORE 3502 4458 -21.4% 5894 19918 -70.4%
8 पर्ना PATNA 0 0 - 0 0 -
9 पुणे PUNE 24431 24303 0.5% 76584 138250 -44.6%
10 वडोदरा VADODARA 23 4 - 29 12 -
योग Total 44439 44863 -0.9% 124801 247231 -49.5%
घिेिू एयिपोर्तस DOMESTIC AIRPORTS
1 आगरा AGRA 0 0 - 53 140 -62.1%
2 भावनगर BHAVNAGAR 0 11 - 0 25 -
3 उदयपुर UDAIPUR 0 18 - 10 18 -44.4%
योग Total 0 29 - 63 183 -65.6%
िरज्य सिकरि / लनजी एयिपोर्तस ST GOVT/PVT AIRPORTS
1 नाझसक (हाल ओजर) NASIK (HAL OZAR) 118 148 -20.3% 777 745 4.3%
योग Total 118 148 -20.3% 777 745 4.3%
कु ि योग Grand Total 6405454 6673252 -4.0% 30597506 33149908 -7.7%
Note:This report is compiled on the basis of data provided by the respective airport and is subject to revision.

======================================================================
PAGE 2
======================================================================
अनुलग्नक-III ख ANNEXURE-III B
घिेिू यरत्री Domestic Passengers
यरत्री (संख्यर में ) Passengers(In Number's)
मरह के लिए For The Month अवलि के लिए For The Period
अगस्त अगस्त अप्रैि से अगस्त
क्र.सं % %
एयिपोर्त Airport August August April To August
S.NO
परिवर्तन परिवर्तन
2026 2025 2026-2027 2025-2026
Change Change
अंर्िरतष्ट्रीय एयिपोर्तस INTERNATIONAL AIRPORTS
1 अमृतसर AMRITSAR 126819 143450 -11.6% 742211 717787 3.4%
2 अयोध्या AYODHYA 36338 54373 -33.2% 249274 402618 -38.1%
3 भुवनेश्वर BHUBANESWAR 310300 376085 -17.5% 1783208 2065043 -13.6%
4 चेन्नई CHENNAI 1192886 1364097 -12.6% 6239276 7061424 -11.6%
5 कोयंबत्तूर COIMBATORE 248014 241409 2.7% 1287843 1362049 -5.4%
6 गोवा GOA (DABOLIM) 430612 447170 -3.7% 2302713 2371935 -2.9%
7 इंफाल IMPHAL 103622 110036 -5.8% 532187 578146 -7.9%
8 कोलकाता KOLKATA 1238469 1424341 -13.0% 7148730 7656086 -6.6%
9 कोझिकोड KOZHIKODE 66333 69962 -5.2% 361990 346099 4.6%
10 कु शीनगर KUSHINAGAR 0 0 - 0 20 -
11 मदुरै MADURAI 95551 89764 6.4% 486726 507089 -4.0%
12 पोर्ट ब्लेयर PORT BLAIR 70741 92806 -23.8% 520192 570588 -8.8%
13 राजकोर् (हीरासर) RAJKOT (HIRASAR) 89032 90688 -1.8% 486501 433694 12.2%
14 श्रीनगर SRINAGAR 221481 257687 -14.1% 1507619 1417344 6.4%
15 सूरत SURAT 105829 129268 -18.1% 639691 650174 -1.6%
16 झतरुझचरापल्ली TIRUCHIRAPPALLI 59573 77354 -23.0% 291031 368129 -20.9%
17 झतरुपझत TIRUPATI 57425 90685 -36.7% 324178 516314 -37.2%
18 वाराणसी VARANASI 268426 291886 -8.0% 1533565 1704009 -10.0%
19 झवजयवाडा VIJAYAWADA 112090 116524 -3.8% 559599 559967 -0.1%
योग Total 4833541 5467585 -11.6% 26996534 29288515 -7.8%
पीपीपी अंर्िरतष्ट्रीय एयिपोर्तस PPP INTERNATIONAL
1 अहमदाबाद AHMEDABAD 718232 869402 -17.4% 4524445 4571120 -1.0%
2 गुवाहार्ी GUWAHATI 459500 489905 -6.2% 2602634 2702638 -3.7%
3 जयपुर JAIPUR 331877 388089 -14.5% 1815966 1806088 0.5%
4 लखनऊ LUCKNOW 337177 372149 -9.4% 2105057 1919313 9.7%
5 मंगलुरु MANGALURU 116267 142396 -18.3% 670896 728302 -7.9%
6 झतरुवनंतपुरम THIRUVANANTHAPURAM 186794 168313 11.0% 871308 922486 -5.5%
योग Total 2149847 2430254 -11.5% 12590306 12649947 -0.5%
संयुक्त उिम एयिपोर्तस JV INTERNATIONAL AIRPORTS
1 बेंगलुरु BENGALURU (BIAL) 2787692 2932526 -4.9% 15104774 15325294 -1.4%
2 झदल्ली (यूर्ी) DELHI (DIAL) 4389269 4259373 3.0% 23869404 22274138 7.2%
3 हैदराबाद HYDERABAD (GHIAL) 1733770 2005921 -13.6% 9379416 10734561 -12.6%
4 कन्नूर (झकयाल) KANNUR (KIAL) 36220 38064 -4.8% 187739 200850 -6.5%
5 कोच्चि KOCHI 488886 460018 6.3% 2383710 2399802 -0.7%
6 मुंबई MUMBAI (MIAL) 2784261 3194908 -12.9% 14513434 15977680 -9.2%
7 नागपुर NAGPUR 214016 224856 -4.8% 1214449 1133360 7.2%
योग Total 12434114 13115666 -5.2% 66652926 68045685 -2.0%
िरज्य सिकरि / लनजी अंर्िरतष्ट्रीय ST GOVT/PVT INTERNATIONAL
1 गोवा (एमओपीए) GOA (MOPA) 276855 359370 -23.0% 1661218 1854901 -10.4%
2 नवी मुंबई NAVI MUMBAI (NMIAL) 352895 0 - 2367902 0 -
3 नोएडा (झनयाल) NOIDA (NIAL) 58520 0 - 155635 0 -
4 झशरडी SHIRDI 47977 51114 -6.1% 238169 276327 -13.8%
5 झवशाखापत्तनम VISAKHAPATNAM (GVIAL) 203500 240807 -15.5% 1104517 1190919 -7.3%
योग Total 939747 651291 44.3% 5527441 3322147 66.4%
सीमर शुल्क एयिपोर्तस CUSTOM AIRPORTS
1 अगरतला AGARTALA 114599 124080 -7.6% 623600 653754 -4.6%
2 औरंगाबाद AURANGABAD 42556 49449 -13.9% 236697 257497 -8.1%
3 बागडोगरा BAGDOGRA 235380 242001 -2.7% 1639923 1456605 12.6%
4 भोपाल BHOPAL 124065 113385 9.4% 654362 626431 4.5%
5 चंडीगढ़ (यूर्ी) CHANDIGARH 272129 281483 -3.3% 1673912 1522591 9.9%
6 गया GAYA 11176 16449 -32.1% 71417 88252 -19.1%
7 इंदौर INDORE 297239 356482 -16.6% 1569728 1702255 -7.8%
8 पर्ना PATNA 285799 329451 -13.2% 1687564 1841348 -8.4%
9 पुणे PUNE 883706 876914 0.8% 4507435 4402187 2.4%
10 वडोदरा VADODARA 82396 95682 -13.9% 482575 488969 -1.3%
योग Total 2349045 2485376 -5.5% 13147213 13039889 0.8%
घिेिू एयिपोर्तस DOMESTIC AIRPORTS
1 आदमपुर (जालंधर) ADAMPUR (JALANDHAR) 10882 7912 37.5% 58270 23254 -
2 अगाती AGATTI 17436 8725 99.8% 76714 47585 61.2%
3 आगरा AGRA 12897 17496 -26.3% 83886 99691 -15.9%

======================================================================
PAGE 3
======================================================================
मरह के लिए For The Month अवलि के लिए For The Period
अगस्त अगस्त अप्रैि से अगस्त
क्र.सं % %
एयिपोर्त Airport August August April To August
S.NO
परिवर्तन परिवर्तन
2026 2025 2026-2027 2025-2026
Change Change
4 बारापानी (झशलांग) BARAPANI (SHILLONG) 5668 6104 -7.1% 35817 34106 5.0%
5 बरेली BAREILLY 12059 10055 19.9% 51942 51761 0.3%
6 बेलगावी BELAGAVI 15091 20825 -27.5% 110999 119614 -7.2%
7 भझर्ंडा BHATINDA 1298 1050 23.6% 4951 7560 -34.5%
8 भावनगर BHAVNAGAR 4724 455 - 28879 17418 65.8%
9 भुज BHUJ 25099 18048 39.1% 128164 98301 30.4%
10 भुंतर (कु ल्लू मनाली) BHUNTAR (KULLU MANALI) 567 363 56.2% 6416 8927 -28.1%
11 बीकानेर BIKANER 4789 4108 16.6% 21356 18892 13.0%
12 कू चझबहर COOCHBEHER 0 426 - 50 2405 -97.9%
13 कडप्पा CUDDAPAH 3128 5815 -46.2% 20062 28652 -30.0%
14 दमन DAMAN 627 0 - 808 0 -
15 दरभंगा DARBHANGA 48063 66826 -28.1% 325256 320990 1.3%
16 देहरादून DEHRADUN 121474 128915 -5.8% 787489 856775 -8.1%
17 देवघर DEOGHAR 23798 26979 -11.8% 147182 159963 -8.0%
18 दीमापुर DIMAPUR 27509 29569 -7.0% 144262 156003 -7.5%
19 दीव DIU 13043 9769 33.5% 63448 48477 30.9%
20 गग्गल (कांगडा) GAGGAL (KANGRA) 12597 7862 60.2% 78545 70885 10.8%
21 गोझंदया GONDIA 26 1355 -98.1% 2011 12409 -83.8%
22 गोरखपुर GORAKHPUR 83752 89781 -6.7% 495586 476967 3.9%
23 ग्वाझलयर GWALIOR 14934 21785 -31.4% 84594 118720 -28.7%
24 झहंडोन HINDON 25886 156537 -83.5% 183768 430139 -57.3%
25 हुबली HUBBALI 28968 26268 10.3% 159775 146024 9.4%
26 हैदराबाद (बेगमपेर्) HYDERABAD (BEGUMPET) 1083 735 47.3% 4741 4696 1.0%
27 ईर्ानगर (होलोगं ी) ITANAGAR (HOLONGI) 14492 14782 -2.0% 86742 75465 14.9%
28 जबलपुर JABALPUR 32866 39065 -15.9% 196161 210636 -6.9%
29 जैसलमेर JAISALMER 44 65 -32.3% 538 222 -
30 जलगांव JALGAON 13744 10444 31.6% 65120 54402 19.7%
31 जम्मू JAMMU 79193 107260 -26.2% 534716 538036 -0.6%
32 जामनगर JAMNAGAR 26974 11927 - 116673 48948 -
33 िारसुगुडा JHARSUGUDA 24347 29497 -17.5% 164723 167471 -1.6%
34 जोधपुर JODHPUR 62333 65007 -4.1% 266244 329352 -19.2%
35 जोरहार् JORHAT 12195 9413 29.6% 72705 49576 46.7%
36 जुहू JUHU 8618 8776 -1.8% 37483 45349 -17.3%
37 कलबुगी (गुलबगाट) KALABURAGI (GULBARGA) 3555 2190 62.3% 8426 11275 -25.3%
38 कांडला KANDLA 15 2293 -99.3% 1124 9817 -88.6%
39 कानपुर (चके री) KANPUR (CHAKERI) 23383 22249 5.1% 143092 151185 -5.4%
40 कानपुर (झसझवल) KANPUR (CIVIL) 0 0 - 0 0 -
41 के शोद (जूनागढ़) KESHOD (JUNAGARH) 448 0 - 1668 1582 5.4%
42 खजुराहो KHAJURAHO 64 276 -76.8% 7085 674 -
43 झकशनगढ़ KISHANGARH 8872 11277 -21.3% 48904 50212 -2.6%
44 कोल्हापुर KOLHAPUR 19778 13828 43.0% 96989 74581 30.0%
45 कोर्ा KOTA 13 1 - 127 37 -
46 लखीमपुर (लीलाबाडी) LAKHIMPUR (LILABARI) 904 364 - 5529 4913 12.5%
47 लेह LEH 120223 101420 18.5% 624938 520707 20.0%
48 लुझधयाना (हलवारा) LUDHIANA (HALWARA) 10756 66 - 38119 563 -
49 मोहनबाडी (झडब्रूगढ़) MOHANBARI (DIBRUGARH) 75505 64841 16.4% 397560 339147 17.2%
50 मुरादाबाद MORADABAD 14 0 - 45 21 -
51 मैसूर MYSURU 5995 5943 0.9% 38543 36059 6.9%
52 पाक्ोगं PAKYONG 0 0 - 0 0 -
53 पंतनगर PANTNAGAR 5192 3602 44.1% 32488 27719 17.2%
54 पठानकोर् PATHANKOT 0 0 - 0 0 -
55 पोरबंदर PORBANDAR 695 531 30.9% 2092 3496 -40.2%
56 प्रयागराज PRAYAGRAJ 27136 39179 -30.7% 180651 234404 -22.9%
57 पुदुचेरी PUDUCHERRY 8157 8753 -6.8% 42387 43536 -2.6%
58 पूझणटया PURNEA 25166 0 - 141007 0 -
59 रायपुर RAIPUR 207946 212378 -2.1% 1104740 1139611 -3.1%
60 राजमुंदरी RAJAHMUNDRY 44652 45802 -2.5% 229067 241334 -5.1%
61 रांची RANCHI 182960 205693 -11.1% 1054816 1139044 -7.4%
62 रीवा REWA 5579 326 - 25172 1713 -
63 रूपसी RUPSI 1714 309 - 4579 2459 86.2%
64 सफदरजंग SAFDARJUNG 0 0 - 12 16 -25.0%
65 सलेम SALEM 11675 9059 28.9% 58681 53923 8.8%
66 सतना SATNA 0 0 - 0 0 -
67 झशमला SHIMLA 26 282 -90.8% 2519 7314 -65.6%
68 शोलापुर SHOLAPUR 840 1654 -49.2% 13644 4294 -

In [9]:

#August 2026 Aircraft Movement Report


MOVEMENT_URL = (
    "https://www.aai.aero/sites/default/files/"
    "traffic-news/Aug2k26Annex2.pdf"
)

movement_response = requests.get(
    MOVEMENT_URL,
    headers={"User-Agent": "Mozilla/5.0"},
    timeout=30
)

print("Status code:", movement_response.status_code)
print("File size:", round(len(movement_response.content) / 1024, 2), "KB")
print("Content type:", movement_response.headers.get("Content-Type"))

Status code: 200
File size: 490.25 KB
Content type: application/pdf

In [10]:

with pdfplumber.open(BytesIO(movement_response.content)) as pdf:

    print("Number of pages:", len(pdf.pages))

    for i, page in enumerate(pdf.pages[:3]):
        text = page.extract_text()

        print(f"\n{'='*70}")
        print(f"PAGE {i + 1}")
        print(f"{'='*70}")

        if text:
            print(text[:5000])
        else:
            print("No text extracted.")

Number of pages: 7

======================================================================
PAGE 1
======================================================================
अनुलग्नक-II क ANNEXURE-II A
अंर्िातष्ट्रीय वायुयान प्रचालन International Aircraft Movement
वायुयान प्रचालन (संख्या में ) AIRCRAFT MOVEMENTS ( IN NOS)
माह के नलए For The Month अवनध के नलए For The Period
अगस्त अगस्त अप्रैल से अगस्त
क्र.सं % %
एयिपोर्त Airport August August April To August
S.NO
परिवर्तन परिवर्तन
2026 2025 2026-2027 2025-2026
Change Change
अंर्िातष्ट्रीय एयिपोर्तस INTERNATIONAL AIRPORTS
1 अमृतसर AMRITSAR 401 472 -15.0% 1891 2437 -22.4%
2 अयोध्या AYODHYA 0 0 - 0 0 -
3 भुवनेश्वर BHUBANESWAR 3 93 -96.8% 280 386 -27.5%
4 चेन्नई CHENNAI 3302 3593 -8.1% 16228 17671 -8.2%
5 कोयंबत्तूर COIMBATORE 140 185 -24.3% 579 882 -34.4%
6 इंफाल IMPHAL 0 0 - 0 0 -
7 गोवा GOA (DABOLIM) 62 112 -44.6% 250 530 -52.8%
8 कोलकाता KOLKATA 1434 1388 3.3% 7681 7383 4.0%
9 कोझिकोड KOZHIKODE 1669 1746 -4.4% 6729 8410 -20.0%
10 कु शीनगर KUSHINAGAR 0 0 - 0 0 -
11 मदुरै MADURAI 76 139 -45.3% 244 628 -61.1%
12 पोर्ट ब्लेयर PORT BLAIR 0 0 - 0 10 -
13 राजकोर् (हीरासर) RAJKOT (HIRASAR) 0 0 - 1 0 -
14 श्रीनगर SRINAGAR 0 0 - 27 32 -15.6%
15 सूरत SURAT 50 125 -60.0% 139 606 -77.1%
16 झतरुझचरापल्ली TIRUCHIRAPPALLI 665 818 -18.7% 3055 4263 -28.3%
17 झतरुपझत TIRUPATI 1 0 - 49 1 -
18 वाराणसी VARANASI 84 92 -8.7% 369 438 -15.8%
19 झवजयवाडा VIJAYAWADA 45 18 - 166 77 -
योग Total 7932 8781 -9.7% 37688 43754 -13.9%
पीपीपी अंर्िातष्ट्रीय एयिपोर्तस PPP INTERNATIONAL
1 अहमदाबाद AHMEDABAD 1059 1392 -23.9% 5230 6980 -25.1%
2 गुवाहार्ी GUWAHATI 92 78 17.9% 476 384 24.0%
3 जयपुर JAIPUR 272 391 -30.4% 1133 1987 -43.0%
4 लखनऊ LUCKNOW 535 576 -7.1% 2520 2954 -14.7%
5 मंगलुरु MANGALURU 427 379 12.7% 1564 1864 -16.1%
6 झतरुवनंतपुरम THIRUVANANTHAPURAM 1378 1367 0.8% 5983 6476 -7.6%
योग Total 3763 4183 -10.0% 16906 20645 -18.1%
संयुक्त उधम एयिपोर्तस JV INTERNATIONAL AIRPORTS
1 बेंगलुरु BENGALURU (BIAL) 3803 3523 7.9% 17506 17585 -0.4%
2 झदल्ली (यूर्ी) DELHI (DIAL) 9851 9432 4.4% 49756 47462 4.8%
3 हैदराबाद HYDERABAD (GHIAL) 2730 2834 -3.7% 12504 13545 -7.7%
4 कन्नूर (झकयाल) KANNUR (KIAL) 561 676 -17.0% 1810 3347 -45.9%
5 कोच्चि KOCHI 2863 2880 -0.6% 11995 13782 -13.0%
6 मुंबई MUMBAI (MIAL) 7373 7909 -6.8% 34916 37911 -7.9%
7 नागपुर NAGPUR 62 64 -3.1% 277 359 -22.8%
योग Total 27243 27318 -0.3% 128764 133991 -3.9%
िाज्य सिकाि / ननजी अंर्िातष्ट्रीय ST GOVT/PVT INTERNATIONAL
1 गोवा (एमओपीए) GOA (MOPA) 106 137 -22.6% 542 865 -37.3%
2 नवी मुंबई NAVI MUMBAI (NMIAL) 66 0 - 77 0 -
3 नोएडा (झनयाल) NOIDA (NIAL) 0 0 - 0 0 -
4 झशरडी SHIRDI 0 0 - 0 0 -
5 झवशाखापत्तनम VISAKHAPATNAM (GVIAL) 50 72 -30.6% 168 323 -48.0%
योग Total 222 209 6.2% 787 1188 -33.8%
सीमा शुल्क एयिपोर्तस CUSTOM AIRPORTS
1 अगरतला AGARTALA 0 0 - 0 0 -
2 औरंगाबाद AURANGABAD 0 0 - 0 0 -
3 बागडोगरा BAGDOGRA 34 48 -29.2% 177 252 -29.8%
4 भोपाल BHOPAL 2 0 - 5 13 -61.5%
5 चंडीगढ़ (यूर्ी) CHANDIGARH 88 88 - 190 412 -53.9%
6 गया GAYA 0 0 - 20 32 -37.5%
7 इंदौर INDORE 38 36 5.6% 66 164 -59.8%
8 पुणे PUNE 233 212 9.9% 707 1093 -35.3%
9 पर्ना PATNA 0 0 - 0 0 -
10 वडोदरा VADODARA 3 1 - 5 2 -
योग Total 398 385 3.4% 1170 1968 -40.5%
घिेलू एयिपोर्तस DOMESTIC AIRPORTS
1 आगरा AGRA 0 0 - 1 6 -83.3%
2 भावनगर BHAVNAGAR 0 2 - 0 4 -
3 उदयपुर UDAIPUR 0 2 - 2 2 -
योग Total 0 4 - 3 12 -75.0%
िाज्य सिकाि / ननजी एयिपोर्तस ST GOVT/PVT AIRPORTS
1 नाझसक (हाल ओजर) NASIK (HAL OZAR) 80 64 25.0% 516 415 24.3%
योग Total 80 64 25.0% 516 415 24.3%
कु ल योग Grand Total 39638 40944 -3.2% 185834 201973 -8.0%
Note:This report is compiled on the basis of data provided by the respective airport and is subject to revision.

======================================================================
PAGE 2
======================================================================
अनुलग्नक-II ख ANNEXURE-II B
घिेलू वायुयान प्रचालन Domestic Aircraft Movement
वायुयान प्रचालन (संख्या में ) AIRCRAFT MOVEMENTS ( IN NOS)
माह के नलए For The Month अवनध के नलए For The Period
अगस्त अगस्त अप्रैल से अगस्त
क्र.सं %
एयिपोर्त Airport August August April To August
S.NO
परिवर्तन परिवर्तन
2026 2025 2026-2027 2025-2026
Change Change
अंर्िातष्ट्रीय एयिपोर्तस INTERNATIONAL AIRPORTS
1 अमृतसर AMRITSAR 1046 986 6.1% 5273 5153 2.3%
2 अयोध्या AYODHYA 240 366 -34.4% 1474 2465 -40.2%
3 भुवनेश्वर BHUBANESWAR 2452 3015 -18.7% 13463 16555 -18.7%
4 चेन्नई CHENNAI 7952 9625 -17.4% 43163 50262 -14.1%
5 कोयंबत्तूर COIMBATORE 1558 1624 -4.1% 8403 8986 -6.5%
6 गोवा GOA (DABOLIM) 2629 2752 -4.5% 13936 15055 -7.4%
7 इंफाल IMPHAL 762 796 -4.3% 3837 4640 -17.3%
8 कोलकाता KOLKATA 8375 9725 -13.9% 46084 50991 -9.6%
9 कोझिकोड KOZHIKODE 480 525 -8.6% 2585 2901 -10.9%
10 कु शीनगर KUSHINAGAR 0 0 - 0 6 -
11 मदुरै MADURAI 602 978 -38.4% 4504 5426 -17.0%
12 पोर्ट ब्लेयर PORT BLAIR 644 1088 -40.8% 4263 5332 -20.0%
13 राजकोर् (हीरासर) RAJKOT (HIRASAR) 796 536 48.5% 4140 2869 44.3%
14 श्रीनगर SRINAGAR 1638 1808 -9.4% 9845 9396 4.8%
15 सूरत SURAT 1200 1390 -13.7% 6556 6772 -3.2%
16 झतरुझचरापल्ली TIRUCHIRAPPALLI 704 885 -20.5% 3588 4364 -17.8%
17 झतरुपझत TIRUPATI 585 1186 -50.7% 3683 5786 -36.3%
18 वाराणसी VARANASI 1658 2056 -19.4% 9195 10884 -15.5%
19 झवजयवाडा VIJAYAWADA 1425 1438 -0.9% 7307 7232 1.0%
योग Total 34746 40779 -14.8% 191299 215075 -11.1%
पीपीपी अंर्िातष्ट्रीय एयिपोर्तस PPP INTERNATIONAL
1 अहमदाबाद AHMEDABAD 5676 6686 -15.1% 32822 35287 -7.0%
2 गुवाहार्ी GUWAHATI 3304 3730 -11.4% 17520 19865 -11.8%
3 जयपुर JAIPUR 2549 2920 -12.7% 13862 14056 -1.4%
4 लखनऊ LUCKNOW 2532 2635 -3.9% 14491 13605 6.5%
5 मंगलुरु MANGALURU 858 1111 -22.8% 5169 5853 -11.7%
6 झतरुवनंतपुरम THIRUVANANTHAPURAM 1208 1186 1.9% 5819 6314 -7.8%
योग Total 16127 18268 -11.7% 89683 94980 -5.6%
संयुक्त उधम एयिपोर्तस JV INTERNATIONAL AIRPORTS
1 बेंगलुरु BENGALURU (BIAL) 17593 18911 -7.0% 95158 99139 -4.0%
2 झदल्ली (यूर्ी) DELHI (DIAL) 30309 26619 13.9% 152683 141113 8.2%
3 हैदराबाद HYDERABAD (GHIAL) 12082 14411 -16.2% 65163 76564 -14.9%
4 कन्नूर (झकयाल) KANNUR (KIAL) 315 456 -30.9% 1831 2357 -22.3%
5 कोच्चि KOCHI 3453 3193 8.1% 16431 16785 -2.1%
6 मुंबई MUMBAI (MIAL) 18644 19509 -4.4% 93884 98991 -5.2%
7 नागपुर NAGPUR 1849 1674 10.5% 9677 8989 7.7%
योग Total 84245 84773 -0.6% 434827 443938 -2.1%
िाज्य सिकाि / ननजी अंर्िातष्ट्रीय ST GOVT/PVT INTERNATIONAL
1 गोवा (एमओपीए) GOA (MOPA) 2128 2669 -20.3% 11483 13362 -14.1%
2 नवी मुंबई NAVI MUMBAI (NMIAL) 2981 0 - 18495 0 -
3 नोएडा (झनयाल) NOIDA (NIAL) 1002 0 - 2255 0 -
4 झशरडी SHIRDI 284 417 -31.9% 1385 2268 -38.9%
5 झवशाखापत्तनम VISAKHAPATNAM (GVIAL) 1577 1806 -12.7% 8123 8922 -9.0%
योग Total 7972 4892 63.0% 41741 24552 70.0%
सीमा शुल्क एयिपोर्तस CUSTOM AIRPORTS
1 अगरतला AGARTALA 792 918 -13.7% 4536 4847 -6.4%
2 औरंगाबाद AURANGABAD 429 408 5.1% 2274 2147 5.9%
3 बागडोगरा BAGDOGRA 1640 1692 -3.1% 10603 9848 7.7%
4 भोपाल BHOPAL 1118 1037 7.8% 5578 5961 -6.4%
5 चंडीगढ़ (यूर्ी) CHANDIGARH 2042 2000 2.1% 11428 10468 9.2%
6 गया GAYA 92 134 -31.3% 583 648 -10.0%
7 इंदौर INDORE 2361 2526 -6.5% 12346 13858 -10.9%
8 पर्ना PATNA 2216 2487 -10.9% 11576 13026 -11.1%
9 पुणे PUNE 6306 5870 7.4% 30537 29154 4.7%
10 वडोदरा VADODARA 616 650 -5.2% 3424 3327 2.9%
योग Total 17612 17722 -0.6% 92885 93284 -0.4%
घिेलू एयिपोर्तस DOMESTIC AIRPORTS
1 आदमपुर (जालंधर) ADAMPUR (JALANDHAR) 124 98 26.5% 604 388 55.7%
2 अगाती AGATTI 472 314 50.3% 2056 1520 35.3%
3 आगरा AGRA 74 168 -56.0% 554 890 -37.8%
4 बारापानी (झशलांग) BARAPANI (SHILLONG) 108 118 -8.5% 640 672 -4.8%
5 बरेली BAREILLY 130 62 - 436 316 38.0%
6 बेलगावी BELAGAVI 257 328 -21.6% 1734 1838 -5.7%
7 भझर्ंडा BHATINDA 42 53 -20.8% 174 413 -57.9%
8 भावनगर BHAVNAGAR 160 93 72.0% 863 667 29.4%

======================================================================
PAGE 3
======================================================================
माह के नलए For The Month अवनध के नलए For The Period
अगस्त अगस्त अप्रैल से अगस्त
क्र.सं %
एयिपोर्त Airport August August April To August
S.NO
परिवर्तन परिवर्तन
2026 2025 2026-2027 2025-2026
Change Change
9 भुज BHUJ 184 146 26.0% 976 872 11.9%
10 भुंतर (कु ल्लू मनाली) BHUNTAR (KULLU MANALI) 98 22 - 523 352 48.6%
11 बीकानेर BIKANER 84 68 23.5% 400 362 10.5%
12 कू चझबहर COOCHBEHER 0 62 - 12 302 -96.0%
13 कडप्पा CUDDAPAH 80 140 -42.9% 535 674 -20.6%
14 दमन DAMAN 32 0 - 38 0 -
15 दरभंगा DARBHANGA 298 446 -33.2% 1958 2160 -9.4%
16 देहरादून DEHRADUN 1172 1154 1.6% 7124 7537 -5.5%
17 देवघर DEOGHAR 239 226 5.8% 1072 1210 -11.4%
18 दीमापुर DIMAPUR 316 342 -7.6% 1963 1714 14.5%
19 दीव DIU 374 264 41.7% 1709 1380 23.8%
20 गग्गल (कांगडा) GAGGAL (KANGRA) 242 146 65.8% 1508 1320 14.2%
21 गोझंदया GONDIA 8 30 -73.3% 94 269 -65.1%
22 गोरखपुर GORAKHPUR 502 534 -6.0% 2940 2944 -0.1%
23 ग्वाझलयर GWALIOR 116 170 -31.8% 686 1014 -32.3%
24 झहंडोन HINDON 358 1168 -69.3% 1954 4044 -51.7%
25 हुबली HUBBALI 441 303 45.5% 2392 1738 37.6%
26 हैदराबाद (बेगमपेर्) HYDERABAD (BEGUMPET) 271 176 54.0% 1292 1180 9.5%
27 ईर्ानगर (होलोगं ी) ITANAGAR (HOLONGI) 146 152 -3.9% 862 778 10.8%
28 जबलपुर JABALPUR 370 424 -12.7% 2085 2385 -12.6%
29 जैसलमेर JAISALMER 10 12 -16.7% 76 42 81.0%
30 जलगांव JALGAON 280 212 32.1% 1328 1116 19.0%
31 जम्मू JAMMU 814 838 -2.9% 5125 4504 13.8%
32 जामनगर JAMNAGAR 362 180 - 2057 799 -
33 िारसुगुडा JHARSUGUDA 203 338 -39.9% 1341 1836 -27.0%
34 जोधपुर JODHPUR 461 414 11.4% 1868 2372 -21.2%
35 जोरहार् JORHAT 98 127 -22.8% 626 585 7.0%
36 जुहू JUHU 1826 1595 14.5% 8489 8770 -3.2%
37 कलबुगी (गुलबगाट) KALABURAGI (GULBARGA) 70 62 12.9% 206 332 -38.0%
38 कांडला KANDLA 4 40 -90.0% 48 202 -76.2%
39 कानपुर (चके री) KANPUR (CHAKERI) 158 170 -7.1% 901 1010 -10.8%
40 कानपुर (झसझवल) KANPUR (CIVIL) 0 0 - 0 0 -
41 के शोद (जूनागढ़) KESHOD (JUNAGARH) 34 0 - 154 128 20.3%
42 खजुराहो KHAJURAHO 13 64 -79.7% 174 198 -12.1%
43 झकशनगढ़ KISHANGARH 173 267 -35.2% 1029 1154 -10.8%
44 कोल्हापुर KOLHAPUR 352 240 46.7% 1688 1398 20.7%
45 कोर्ा KOTA 4 2 - 42 10 -
46 लखीमपुर (लीलाबाडी) LAKHIMPUR (LILABARI) 38 16 - 171 112 52.7%
47 लेह LEH 1012 852 18.8% 4948 4172 18.6%
48 लुझधयाना (हलवारा) LUDHIANA (HALWARA) 124 17 - 432 185 -
49 मोहनबाडी (झडब्रूगढ़) MOHANBARI (DIBRUGARH) 604 526 14.8% 3030 2685 12.8%
50 मुरादाबाद MORADABAD 2 0 - 8 6 33.3%
51 मैसूर MYSURU 148 118 25.4% 711 664 7.1%
52 पाक्ोगं PAKYONG 0 0 - 0 0 -
53 पंतनगर PANTNAGAR 126 84 50.0% 750 604 24.2%
54 पठानकोर् PATHANKOT 0 0 - 0 0 -
55 पोरबंदर PORBANDAR 32 22 45.5% 106 100 6.0%
56 प्रयागराज PRAYAGRAJ 188 295 -36.3% 1187 1688 -29.7%
57 पुदुचेरी PUDUCHERRY 124 122 1.6% 696 615 13.2%
58 पूझणटया PURNEA 311 0 - 1499 0 -
59 रायपुर RAIPUR 1671 1647 1.5% 8690 9196 -5.5%
60 राजमुंदरी RAJAHMUNDRY 692 698 -0.9% 3744 3500 7.0%
61 रांची RANCHI 1355 1535 -11.7% 7486 7870 -4.9%
62 रीवा REWA 176 74 - 730 430 69.8%
63 रूपसी RUPSI 42 10 - 114 78 46.2%
64 सफदरजंग SAFDARJUNG 5 8 -37.5% 43 29 48.3%
65 सलेम SALEM 258 192 34.4% 1276 1072 19.0%
66 सतना SATNA 0 0 - 0 0 -
67 झशमला SHIMLA 14 24 -41.7% 194 326 -40.5%
68 शोलापुर SHOLAPUR 31 46 -32.6% 417 150 -
69 झसलचर SILCHAR 248 207 19.8% 1298 1223 6.1%
70 तेजपुर TEZPUR 0 0 - 0 0 -
71 तेजु TEZU 32 18 77.8% 148 208 -28.8%
72 तूतीकोररन TUTICORIN 311 422 -26.3% 1615 2086 -22.6%
73 उदयपुर UDAIPUR 917 791 15.9% 4420 4181 5.7%
योग Total 20021 19492 2.7% 106049 104575 1.4%
िाज्य सिकाि / ननजी एयिपोर्तस ST GOVT/PVT AIRPORTS
1 आइजोल (लेंगपुई) AIZAWL(LENGPUI) 286 281 1.8% 1440 1621 -11.2%
2 अलीगढ ALIGARH 2 4 -50.0% 2 17 -88.2%

In [11]:
FREIGHT_URL = (
    "https://www.aai.aero/sites/default/files/"
    "traffic-news/Aug2k26Annex_4.pdf"
)

freight_response = requests.get(
    FREIGHT_URL,
    headers={"User-Agent": "Mozilla/5.0"},
    timeout=30
)

print("Status code:", freight_response.status_code)
print("File size:", round(len(freight_response.content) / 1024, 2), "KB")
print("Content type:", freight_response.headers.get("Content-Type"))

Status code: 200
File size: 128.23 KB
Content type: application/pdf

In [12]:
with pdfplumber.open(BytesIO(freight_response.content)) as pdf:

    print("Number of pages:", len(pdf.pages))

    for i, page in enumerate(pdf.pages[:3]):
        text = page.extract_text()

        print(f"\n{'='*70}")
        print(f"PAGE {i + 1}")
        print(f"{'='*70}")

        if text:
            print(text[:5000])
        else:
            print("No text extracted.")

Number of pages: 7

======================================================================
PAGE 1
======================================================================
अनलु @नक-IV क ANNEXURE-IV A
अंतरा(cid:9)(cid:25)(cid:26)(cid:27)य माल International Freight
माल (म&ै(cid:26)क टन म') Freight (In MT )
माह के *लए For The Month अव+ध के *लए For The Period
(.स ं
एयरपोट(cid:9) Airport A
अ
u
ग
g
(cid:3)
u
त
s t A
अ
u
ग
g
(cid:3)
u
त
s t
%
Ap
अ
r
,
il
ैल
T
स
o
े अ
A
ग
u
(cid:3)
g
त
u st
%
S.NO
2026 2025 प(cid:6)रवतन(cid:9) Change 2026-2027 2025-2026
प(cid:6)रवतन(cid:9)
Change
अंतरा(cid:9)(cid:25)(cid:26)(cid:27)य एयरपोट(cid:9)स INTERNATIONAL AIRPORTS
1अमतृ सर AMRITSAR 187.6 158.3 18.5% 885.8 760.5 16.5%
2अयो(cid:9)या AYODHYA 0.0 0.0 - 0.0 0.0 -
3भवु ने(cid:16)वर BHUBANESWAR 0.0 5.6 - 0.0 49.0 -
4चे(cid:18)नई CHENNAI 33955.1 27609.9 23.0% 158280.3 139395.6 13.5%
5कोयबं (cid:23)रू COIMBATORE 140.9 172.3 -18.2% 756.2 924.1 -18.2%
6गोवा GOA (DABOLIM) 2.3 47.6 -95.3% 28.6 138.9 -79.4%
7इंफाल IMPHAL 0.0 0.0 - 0.0 0.0 -
8कोलकाता KOLKATA 4713.7 4947.5 -4.7% 21527.2 20824.8 3.4%
9को(cid:29)झकोड KOZHIKODE 1505.4 1700.4 -11.5% 6312.4 8361.9 -24.5%
10कुशीनगर KUSHINAGAR 0.0 0.0 - 0.0 0.0 -
11मदरुै MADURAI 79.6 72.5 9.7% 280.0 692.2 -59.5%
12पोट& 'लेयर PORT BLAIR 0.0 0.0 - 0.0 0.0 -
13राजकोट (ह*रासर) RAJKOT (HIRASAR) 0.0 0.0 - 0.0 0.0 -
14+ीनगर SRINAGAR 6.4 10.8 -40.7% 45.6 46.7 -2.4%
15सरूत SURAT 0.0 0.0 - 0.0 0.0 -
16,त-.चराप/ल* TIRUCHIRAPPALLI 722.3 626.9 15.2% 3005.4 2952.5 1.8%
17,त-प,त TIRUPATI 0.0 0.0 - 0.0 0.0 -
18वाराणसी VARANASI 111.3 82.6 34.7% 375.9 508.8 -26.1%
191वजयवाड़ा VIJAYAWADA 0.0 0.0 - 0.0 0.0 -
योग Total 41424.6 35434.3 16.9% 191497.2 174655.1 9.6%
पीपीपी अंतरा(cid:9)(cid:25)(cid:26)(cid:27)य एयरपोट(cid:9)स PPP INTERNATIONAL
1अहमदाबाद AHMEDABAD 6786.8 6089.8 11.4% 31381.3 24107.5 30.2%
2गवु ाहाट* GUWAHATI 0.3 2.2 -87.5% 2.8 3.7 -25.3%
3जयपुर JAIPUR 190.1 127.5 49.0% 686.1 878.3 -21.9%
4लखनऊ LUCKNOW 538.0 497.8 8.1% 2348.2 2435.7 -3.6%
5मगं ल-ु MANGALURU 200.6 219.5 -8.6% 439.0 542.2 -19.0%
6,त-वनतं पुरम THIRUVANANTHAPURAM 1532.4 1875.7 -18.3% 6695.9 8304.4 -19.4%
योग Total 9248.1 8812.5 4.9% 41553.3 36271.8 14.6%
सयं (cid:28)ु त उधम एयरपोट(cid:9)स JV INTERNATIONAL AIRPORTS
1ब5गल-ु BENGALURU (BIAL) 34914.0 28304.0 23.4% 166474.0 140741.0 18.3%
26द/ल* (यटू *) DELHI (DIAL) 71765.3 62727.1 14.4% 350406.5 306936.1 14.2%
3हैदराबाद HYDERABAD (GHIAL) 11640.6 8725.1 33.4% 56520.2 41546.7 36.0%
4क(cid:18)नरू (7कयाल) KANNUR (KIAL) 242.3 417.8 -42.0% 742.5 1881.3 -60.5%
5कोि9च KOCHI 5146.0 5251.0 -2.0% 25496.0 23295.5 9.4%
6मबुं ई MUMBAI (MIAL) 64565.3 57820.5 11.7% 321439.4 283843.4 13.2%
7नागपुर NAGPUR 7.2 5.4 32.3% 35.7 41.1 -13.0%
योग Total 188280.6 163250.9 15.3% 921114.4 798285.0 15.4%
रा(cid:12)य सरकार / (cid:16)नजी अंतरा(cid:9)(cid:25)(cid:26)(cid:27)य ST GOVT/PVT INTERNATIONAL
1गोवा (एमओपीए) GOA (MOPA) 96.8 56.7 70.5% 533.2 792.4 -32.7%
2नवी मबुं ई NAVI MUMBAI (NMIAL) 664.8 0.0 - 668.7 0.0 -
3नोएडा (,नयाल) NOIDA (NIAL) 0.0 0.0 - 0.0 0.0 -
4<शरडी SHIRDI 0.0 0.0 - 0.0 0.0 -
51वशाखाप(cid:23)नम VISAKHAPATNAM (GVIAL) 0.0 0.0 - 0.0 0.0 -
योग Total 761.6 56.7 - 1201.9 792.4 51.7%
सीमा शु!क एयरपोट(cid:9)स CUSTOM AIRPORTS
1अगरतला AGARTALA 0.0 0.0 - 0.0 0.0 -
2औरंगाबाद AURANGABAD 0.0 0.0 - 0.0 0.0 -
3बागडोगरा BAGDOGRA 0.0 0.0 - 0.0 0.0 -
4भोपाल BHOPAL 0.0 0.0 - 0.0 0.0 -
5चंडीगढ़ (यटू *) CHANDIGARH 0.0 0.0 - 0.0 0.0 -
6गया GAYA 0.0 0.0 - 0.0 0.0 -
7इंदौर INDORE 0.0 0.0 - 0.0 0.0 -
8पटना PATNA 0.0 0.0 - 0.0 0.0 -
9पुणे PUNE 31.3 2.7 - 137.4 40.6 -
10वडोदरा VADODARA 0.0 0.0 - 0.0 0.0 -
योग Total 31.3 2.7 - 137.4 40.6 -
घरेल ूएयरपोट(cid:9)स DOMESTIC AIRPORTS
योग Total 0.0 0.0 - 0.0 0.0 -
रा(cid:12)य सरकार / (cid:16)नजी एयरपोट(cid:9)स ST GOVT/PVT AIRPORTS
1ना<सक (हाल ओजर) NASIK (HAL OZAR) 665.9 565.4 17.8% 4230.3 3586.3 18.0%
योग Total 665.9 565.4 17.8% 4230.3 3586.3 18.0%
कुल योग Grand Total 240412.1 208122.6 15.5% 1159734.5 1013631.2 14.4%
Note:This report is compiled on the basis of data provided by the respective airport and is subject to revision.

======================================================================
PAGE 2
======================================================================
अनुल@नक-IV ख ANNEXURE-IV B
घरेल ूमाल Domestic Freight
माल (म&ै(cid:26)क टन म') Freight (In MT )
माह के *लए For The Month अव+ध के *लए For The Period
(.स ं
एयरपोट(cid:9) Airport A
अ
u
ग
g
(cid:3)
u
त
s t A
अ
u
ग
g
(cid:3)
u
त
s t
%
Ap
अ
r
,
il
ैल
T
स
o
े अ
A
ग
u
(cid:3)
g
त
u st
%
S.NO
प(cid:6)रवतन(cid:9) प(cid:6)रवतन(cid:9)
2026 2025 2026-2027 2025-2026
Change Change
अतं रा(cid:9)(cid:25)(cid:26)(cid:27)य एयरपोट(cid:9)स INTERNATIONAL AIRPORTS
1अमतृ सर AMRITSAR 115.4 133.9 -13.8% 949.2 780.4 21.6%
2अयो(cid:9)या AYODHYA 0.0 0.0 - 0.0 0.0 -
3भवु ने(cid:16)वर BHUBANESWAR 856.7 734.8 16.6% 4368.9 3924.9 11.3%
4चे(cid:18)नई CHENNAI 7924.4 8593.6 -7.8% 41447.7 41254.1 0.5%
5कोयंब(cid:23)रू COIMBATORE 948.8 1015.3 -6.6% 4594.0 4460.5 3.0%
6गोवा GOA (DABOLIM) 463.6 420.6 10.2% 2537.0 2009.5 26.3%
7इंफाल IMPHAL 453.9 568.4 -20.1% 2724.4 2653.2 2.7%
8कोलकाता KOLKATA 9937.3 9763.2 1.8% 51497.9 48971.2 5.2%
9को(cid:29)झकोड KOZHIKODE 0.0 31.0 - 1.4 36.6 -96.2%
10कुशीनगर KUSHINAGAR 0.0 0.0 - 0.0 0.0 -
11मदरुै MADURAI 309.6 199.9 54.9% 1563.1 874.4 78.8%
12पोट& 'लेयर PORT BLAIR 545.6 650.1 -16.1% 3243.6 3178.4 2.1%
13राजकोट (ह*रासर) RAJKOT (HIRASAR) 194.1 57.9 - 931.1 225.0 -
14+ीनगर SRINAGAR 484.2 641.8 -24.6% 3734.6 4666.7 -20.0%
15सरू त SURAT 686.8 794.9 -13.6% 4028.1 3483.5 15.6%
16,त-.चराप/ल* TIRUCHIRAPPALLI 11.0 0.0 - 11.0 0.0 -
17,त-प,त TIRUPATI 33.4 13.6 - 193.8 111.5 73.9%
18वाराणसी VARANASI 502.4 548.9 -8.5% 2206.1 2479.3 -11.0%
191वजयवाड़ा VIJAYAWADA 146.9 92.7 58.4% 646.9 481.9 34.2%
योग Total 23614.1 24260.5 -2.7% 124678.6 119590.9 4.3%
पीपीपी अतं रा(cid:9)(cid:25)(cid:26)(cid:27)य एयरपोट(cid:9)स PPP INTERNATIONAL
1अहमदाबाद AHMEDABAD 6207.0 5736.1 8.2% 32651.6 29588.1 10.4%
2गुवाहाट* GUWAHATI 2677.3 2568.7 4.2% 12514.9 11660.8 7.3%
3जयपुर JAIPUR 2170.7 2255.7 -3.8% 10968.8 9086.1 20.7%
4लखनऊ LUCKNOW 1588.0 1363.2 16.5% 8080.2 7142.4 13.1%
5मगं ल-ु MANGALURU 53.7 63.7 -15.6% 309.2 170.7 81.1%
6,त-वनंतपुरम THIRUVANANTHAPURAM 381.3 294.1 29.7% 1765.5 1233.7 43.1%
योग Total 13078.1 12281.3 6.5% 66290.2 58881.9 12.6%
सयं ु(cid:28)त उधम एयरपोट(cid:9)स JV INTERNATIONAL AIRPORTS
1ब5गल-ु BENGALURU (BIAL) 18530.0 16656.0 11.3% 89225.0 79768.0 11.9%
26द/ल* (यूट*) DELHI (DIAL) 34660.3 33510.8 3.4% 172245.2 161711.5 6.5%
3हैदराबाद HYDERABAD (GHIAL) 5848.5 6232.5 -6.2% 29719.7 30580.9 -2.8%
4क(cid:18)नूर (7कयाल) KANNUR (KIAL) 5.7 2.6 - 33.0 21.5 53.3%
5कोि9च KOCHI 1357.8 1627.5 -16.6% 7101.8 6616.6 7.3%
6मबुं ई MUMBAI (MIAL) 16967.0 17968.0 -5.6% 90282.0 96840.3 -6.8%
7नागपुर NAGPUR 609.7 850.3 -28.3% 3350.2 4098.6 -18.3%
योग Total 77979.1 76847.6 1.5% 391956.9 379637.3 3.2%
रा(cid:12)य सरकार / (cid:16)नजी अतं रा(cid:9)(cid:25)(cid:26)(cid:27)य ST GOVT/PVT INTERNATIONAL
1गोवा (एमओपीए) GOA (MOPA) 48.4 165.8 -70.8% 402.0 542.8 -25.9%
2नवी मबुं ई NAVI MUMBAI (NMIAL) 748.4 0.0 - 4103.9 0.0 -
3नोएडा (,नयाल) NOIDA (NIAL) 150.9 0.0 - 365.6 0.0 -
4<शरडी SHIRDI 7.6 5.5 38.1% 31.9 26.9 18.5%
51वशाखाप(cid:23)नम VISAKHAPATNAM (GVIAL) 341.6 365.1 -6.4% 1905.4 2249.9 -15.3%
योग Total 1296.8 536.3 - 6808.8 2819.6 -
सीमा शु!क एयरपोट(cid:9)स CUSTOM AIRPORTS
1अगरतला AGARTALA 426.9 422.2 1.1% 2655.3 2691.4 -1.3%
2औरंगाबाद AURANGABAD 182.8 120.2 52.1% 682.0 487.9 39.8%
3बागडोगरा BAGDOGRA 1034.2 867.8 19.2% 5265.7 4182.9 25.9%
4भोपाल BHOPAL 185.3 207.7 -10.8% 996.6 1003.6 -0.7%
5चंडीगढ़ (यूट*) CHANDIGARH 1445.8 1134.0 27.5% 9570.5 6239.9 53.4%
6गया GAYA 0.0 0.0 - 0.0 0.0 -
7इंदौर INDORE 997.1 1061.9 -6.1% 4553.8 4716.8 -3.5%
8पटना PATNA 783.6 923.8 -15.2% 4382.2 5202.0 -15.8%
9पुणे PUNE 6015.7 4142.7 45.2% 29180.7 20086.1 45.3%
10वडोदरा VADODARA 295.9 155.3 90.6% 999.6 907.3 10.2%

======================================================================
PAGE 3
======================================================================
माह के *लए For The Month अव+ध के *लए For The Period
(.स ं
एयरपोट(cid:9) Airport A
अ
u
ग
g
(cid:3)
u
त
s t A
अ
u
ग
g
(cid:3)
u
त
s t
%
Ap
अ
r
,
il
ैल
T
स
o
े अ
A
ग
u
(cid:3)
g
त
u st
%
S.NO
प(cid:6)रवतन(cid:9) प(cid:6)रवतन(cid:9)
2026 2025 2026-2027 2025-2026
Change Change
योग Total 11367.2 9035.6 25.8% 58286.2 45517.9 28.1%
घरेल ूएयरपोट(cid:9)स DOMESTIC AIRPORTS
1आदमपुर (जालधं र) ADAMPUR (JALANDHAR) 0.0 0.0 - 0.0 0.0 -
2अगाती AGATTI 0.0 0.0 - 0.0 0.0 -
3आगरा AGRA 26.3 9.1 - 131.7 51.8 -
4बारापानी (<शलांग) BARAPANI (SHILLONG) 0.0 0.0 - 0.0 0.0 -
5बरेल* BAREILLY 0.0 0.0 - 0.0 0.0 -
6बेलगावी BELAGAVI 1.5 0.9 59.6% 10.8 2.8 -
7भ6टडं ा BHATINDA 0.0 0.0 - 0.0 0.0 -
8भावनगर BHAVNAGAR 0.0 0.0 - 0.0 0.0 -
9भजु BHUJ 0.8 0.1 - 1.9 1.5 25.4%
10भतुं र (कु/ल ूमनाल*) BHUNTAR (KULLU MANALI) 0.0 0.0 - 0.0 0.0 -
11बीकानेर BIKANER 0.0 0.0 - 0.0 0.0 -
12कूचCबहर COOCHBEHER 0.0 0.0 - 0.0 0.0 -
13कडDपा CUDDAPAH 0.0 0.0 - 0.0 0.0 -
14दमन DAMAN 0.0 0.0 - 0.0 0.0 -
15दरभगं ा DARBHANGA 48.7 26.6 82.9% 522.8 370.4 41.1%
16देहरादनू DEHRADUN 103.5 105.5 -1.9% 857.9 982.7 -12.7%
17देवघर DEOGHAR 0.0 0.0 - 0.0 0.0 -
18द*मापुर DIMAPUR 88.3 117.1 -24.6% 547.8 510.9 7.2%
19द*व DIU 0.0 0.0 - 0.0 0.0 -
20ग@गल (कांगड़ा) GAGGAL (KANGRA) 0.0 0.0 - 0.0 0.0 -
21गF6दया GONDIA 0.0 0.0 - 0.0 0.0 -
22गोरखपुर GORAKHPUR 0.0 0.0 - 0.0 0.0 -
23@वा<लयर GWALIOR 0.0 0.0 - 0.0 0.0 -
246हडं ोन HINDON 0.0 0.0 - 0.0 0.0 -
25हुबल* HUBBALI 11.3 13.8 -18.0% 76.3 95.2 -19.8%
26हैदराबाद (बेगमपेट) HYDERABAD (BEGUMPET) 0.0 0.0 - 0.0 0.0 -
27ईटानगर (होलFगी) ITANAGAR (HOLONGI) 2.3 2.6 -12.3% 14.3 4.3 -
28जबलपुर JABALPUR 9.5 0.0 - 50.2 0.0 -
29जसै लमेर JAISALMER 0.0 0.0 - 0.0 0.0 -
30जलगांव JALGAON 0.0 0.0 - 0.0 0.0 -
31जGम ूJAMMU 81.6 98.4 -17.0% 438.9 188.6 -
32जामनगर JAMNAGAR 25.9 4.6 - 75.5 74.1 1.9%
33झारसगु ुडा JHARSUGUDA 0.0 0.0 - 0.0 0.0 -
34जोधपुर JODHPUR 13.6 9.9 37.7% 49.0 47.3 3.6%
35जोरहाट JORHAT 9.2 13.9 -33.9% 28.5 52.8 -46.0%
36जहु ू JUHU 18.0 21.2 -14.9% 83.0 110.5 -24.8%
37कलबुगH (गुलबगा&) KALABURAGI (GULBARGA) 0.0 0.0 - 0.0 0.0 -
38कांडला KANDLA 0.0 0.0 - 0.0 0.0 -
39कानपुर (चकेर*) KANPUR (CHAKERI) 7.4 17.9 -58.6% 52.8 108.4 -51.3%
40कानपुर (<स1वल) KANPUR (CIVIL) 0.0 0.0 - 0.0 0.0 -
41केशोद (जनू ागढ़) KESHOD (JUNAGARH) 0.0 0.0 - 0.0 0.0 -
42खजरु ाहो KHAJURAHO 0.0 0.0 - 0.0 0.0 -
437कशनगढ़ KISHANGARH 0.0 0.0 - 0.0 0.0 -
44को/हापुर KOLHAPUR 0.0 0.0 - 0.0 0.0 -
45कोटा KOTA 0.0 0.0 - 0.0 0.0 -
46लखीमपुर (ल*लाबाड़ी) LAKHIMPUR (LILABARI) 0.0 0.0 - 0.0 0.0 -
47लेह LEH 158.8 133.5 19.0% 707.4 601.8 17.5%
48ल.ुधयाना (हलवारा) LUDHIANA (HALWARA) 0.0 0.0 - 0.0 0.0 -
49मोहनबाड़ी (IडJूगढ़) MOHANBARI (DIBRUGARH) 133.7 109.7 21.9% 590.5 478.9 23.3%
50मरु ादाबाद MORADABAD 0.0 0.0 - 0.0 0.0 -
51मसै रू MYSURU 0.0 0.0 - 0.0 0.0 -
52पंतनगर PANTNAGAR 0.0 0.0 - 0.0 0.0 -
53पाKयFग PAKYONG 0.0 0.0 - 0.0 0.0 -
54पठानकोट PATHANKOT 0.0 0.0 - 0.0 0.0 -
55पोरबंदर PORBANDAR 0.0 0.0 - 0.0 0.0 -
56Mयागराज PRAYAGRAJ 3.3 3.4 -2.9% 18.5 15.7 18.2%
57पुदचु ेर* PUDUCHERRY 0.0 0.0 - 0.0 0.0 -
58पू(cid:29)णय& ा PURNEA 0.0 0.0 - 0.0 0.0 -
59रायपुर RAIPUR 453.5 444.2 2.1% 2346.2 2132.9 10.0%
60राजमदुं र* RAJAHMUNDRY 3.7 2.4 53.1% 30.3 14.5 -
61रांची RANCHI 663.9 708.5 -6.3% 3135.6 3093.8 1.4%

In [13]:
def extract_pdf_text(pdf_bytes):
    """
    Extract text from all pages of an AAI PDF.
    Returns a list containing page-level text.
    """

    pages_text = []

    with pdfplumber.open(BytesIO(pdf_bytes)) as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            pages_text.append(text if text else "")

    return pages_text


passenger_pages = extract_pdf_text(pdf_response.content)
movement_pages = extract_pdf_text(movement_response.content)
freight_pages = extract_pdf_text(freight_response.content)

print("Passenger pages:", len(passenger_pages))
print("Movement pages:", len(movement_pages))
print("Freight pages:", len(freight_pages))

Passenger pages: 7
Movement pages: 7
Freight pages: 7

In [14]:
def find_rgya_lines(pages_text):
    """
    Find lines containing Hyderabad (GHIAL)
    or Hyderabad GHIAL references.
    """

    matches = []

    for page_no, page_text in enumerate(pages_text, start=1):
        for line in page_text.splitlines():
            if "HYDERABAD (GHIAL)" in line.upper():
                matches.append({
                    "page": page_no,
                    "line": line
                })

    return matches


print("PASSENGER RGIA:")
for x in find_rgya_lines(passenger_pages):
    print(x)

print("\nMOVEMENT RGIA:")
for x in find_rgya_lines(movement_pages):
    print(x)

print("\nFREIGHT RGIA:")
for x in find_rgya_lines(freight_pages):
    print(x)

PASSENGER RGIA:
{'page': 1, 'line': '3 हैदराबाद HYDERABAD (GHIAL) 452164 464341 -2.6% 2117531 2261073 -6.3%'}
{'page': 2, 'line': '3 हैदराबाद HYDERABAD (GHIAL) 1733770 2005921 -13.6% 9379416 10734561 -12.6%'}
{'page': 5, 'line': '3 हैदराबाद HYDERABAD (GHIAL) 2185934 2470262 -11.5% 11496947 12995634 -11.5%'}

MOVEMENT RGIA:
{'page': 1, 'line': '3 हैदराबाद HYDERABAD (GHIAL) 2730 2834 -3.7% 12504 13545 -7.7%'}
{'page': 2, 'line': '3 हैदराबाद HYDERABAD (GHIAL) 12082 14411 -16.2% 65163 76564 -14.9%'}
{'page': 5, 'line': '3 हैदराबाद HYDERABAD (GHIAL) 14812 17245 -14.1% 77667 90109 -13.8%'}

FREIGHT RGIA:
{'page': 1, 'line': '3हैदराबाद HYDERABAD (GHIAL) 11640.6 8725.1 33.4% 56520.2 41546.7 36.0%'}
{'page': 2, 'line': '3हैदराबाद HYDERABAD (GHIAL) 5848.5 6232.5 -6.2% 29719.7 30580.9 -2.8%'}
{'page': 5, 'line': '3हैदराबाद HYDERABAD (GHIAL) 17489.1 14957.6 16.9% 86240.0 72127.6 19.6%'}

In [15]:
import re
import pandas as pd


def parse_rgya_line(line):
    """
    Extract the six numeric fields from an RGIA HYDERABAD (GHIAL) row.

    Expected structure:
    Airport
    current_month
    previous_year_month
    monthly_change
    current_period
    previous_year_period
    period_change
    """

    # Remove serial number and airport name
    line_clean = re.sub(
        r"^\s*\d+\s*.*?HYDERABAD\s*\(GHIAL\)\s*",
        "",
        line,
        flags=re.IGNORECASE
    )

    # Extract numeric values
    values = re.findall(
        r"-?\d+(?:\.\d+)?%?",
        line_clean
    )

    if len(values) != 6:
        return None

    return {
        "month_current": float(values[0].replace("%", "")),
        "month_previous_year": float(values[1].replace("%", "")),
        "month_change_pct": float(values[2].replace("%", "")),
        "period_current": float(values[3].replace("%", "")),
        "period_previous_year": float(values[4].replace("%", "")),
        "period_change_pct": float(values[5].replace("%", ""))
    }

In [16]:
test_lines = [
    "3 हैदराबाद HYDERABAD (GHIAL) 452164 464341 -2.6% 2117531 2261073 -6.3%",
    "3 हैदराबाद HYDERABAD (GHIAL) 1733770 2005921 -13.6% 9379416 10734561 -12.6%",
    "3 हैदराबाद HYDERABAD (GHIAL) 2185934 2470262 -11.5% 11496947 12995634 -11.5%",

    "3 हैदराबाद HYDERABAD (GHIAL) 2730 2834 -3.7% 12504 13545 -7.7%",
    "3 हैदराबाद HYDERABAD (GHIAL) 12082 14411 -16.2% 65163 76564 -14.9%",
    "3 हैदराबाद HYDERABAD (GHIAL) 14812 17245 -14.1% 77667 90109 -13.8%",

    "3हैदराबाद HYDERABAD (GHIAL) 11640.6 8725.1 33.4% 56520.2 41546.7 36.0%",
    "3हैदराबाद HYDERABAD (GHIAL) 5848.5 6232.5 -6.2% 29719.7 30580.9 -2.8%",
    "3हैदराबाद HYDERABAD (GHIAL) 17489.1 14957.6 16.9% 86240.0 72127.6 19.6%"
]

for line in test_lines:
    print(parse_rgya_line(line))

{'month_current': 452164.0, 'month_previous_year': 464341.0, 'month_change_pct': -2.6, 'period_current': 2117531.0, 'period_previous_year': 2261073.0, 'period_change_pct': -6.3}
{'month_current': 1733770.0, 'month_previous_year': 2005921.0, 'month_change_pct': -13.6, 'period_current': 9379416.0, 'period_previous_year': 10734561.0, 'period_change_pct': -12.6}
{'month_current': 2185934.0, 'month_previous_year': 2470262.0, 'month_change_pct': -11.5, 'period_current': 11496947.0, 'period_previous_year': 12995634.0, 'period_change_pct': -11.5}
{'month_current': 2730.0, 'month_previous_year': 2834.0, 'month_change_pct': -3.7, 'period_current': 12504.0, 'period_previous_year': 13545.0, 'period_change_pct': -7.7}
{'month_current': 12082.0, 'month_previous_year': 14411.0, 'month_change_pct': -16.2, 'period_current': 65163.0, 'period_previous_year': 76564.0, 'period_change_pct': -14.9}
{'month_current': 14812.0, 'month_previous_year': 17245.0, 'month_change_pct': -14.1, 'period_current': 77667.0, 'period_previous_year': 90109.0, 'period_change_pct': -13.8}
{'month_current': 11640.6, 'month_previous_year': 8725.1, 'month_change_pct': 33.4, 'period_current': 56520.2, 'period_previous_year': 41546.7, 'period_change_pct': 36.0}
{'month_current': 5848.5, 'month_previous_year': 6232.5, 'month_change_pct': -6.2, 'period_current': 29719.7, 'period_previous_year': 30580.9, 'period_change_pct': -2.8}
{'month_current': 17489.1, 'month_previous_year': 14957.6, 'month_change_pct': 16.9, 'period_current': 86240.0, 'period_previous_year': 72127.6, 'period_change_pct': 19.6}

In [17]:
for name, pages in [
    ("Passengers", passenger_pages),
    ("Aircraft Movements", movement_pages),
    ("Freight", freight_pages)
]:

    print(f"\n{'='*70}")
    print(name.upper())
    print(f"{'='*70}")

    for page_no in [1, 2, 5]:
        print(f"\nPAGE {page_no}")

        for line in pages[page_no - 1].splitlines():
            if "HYDERABAD" in line.upper() and "GHIAL" in line.upper():
                print(line)

======================================================================
PASSENGERS
======================================================================

PAGE 1
3 हैदराबाद HYDERABAD (GHIAL) 452164 464341 -2.6% 2117531 2261073 -6.3%

PAGE 2
3 हैदराबाद HYDERABAD (GHIAL) 1733770 2005921 -13.6% 9379416 10734561 -12.6%

PAGE 5
3 हैदराबाद HYDERABAD (GHIAL) 2185934 2470262 -11.5% 11496947 12995634 -11.5%

======================================================================
AIRCRAFT MOVEMENTS
======================================================================

PAGE 1
3 हैदराबाद HYDERABAD (GHIAL) 2730 2834 -3.7% 12504 13545 -7.7%

PAGE 2
3 हैदराबाद HYDERABAD (GHIAL) 12082 14411 -16.2% 65163 76564 -14.9%

PAGE 5
3 हैदराबाद HYDERABAD (GHIAL) 14812 17245 -14.1% 77667 90109 -13.8%

======================================================================
FREIGHT
======================================================================

PAGE 1
3हैदराबाद HYDERABAD (GHIAL) 11640.6 8725.1 33.4% 56520.2 41546.7 36.0%

PAGE 2
3हैदराबाद HYDERABAD (GHIAL) 5848.5 6232.5 -6.2% 29719.7 30580.9 -2.8%

PAGE 5
3हैदराबाद HYDERABAD (GHIAL) 17489.1 14957.6 16.9% 86240.0 72127.6 19.6%

In [18]:
def parse_rgya_line(line):
    """
    Parse an AAI RGIA row containing:

    month_current
    month_previous_year
    month_change_pct
    period_current
    period_previous_year
    period_change_pct
    """

    # Find the part after HYDERABAD (GHIAL)
    match = re.search(
        r"HYDERABAD\s*\(GHIAL\)\s*(.*)$",
        line,
        flags=re.IGNORECASE
    )

    if not match:
        return None

    values = match.group(1).strip().split()

    if len(values) < 6:
        return None

    def parse_number(value):
        value = value.replace(",", "")
        return float(value)

    def parse_pct(value):
        value = value.replace("%", "")

        if value == "-":
            return np.nan

        return float(value)

    return {
        "month_current": parse_number(values[0]),
        "month_previous_year": parse_number(values[1]),
        "month_change_pct": parse_pct(values[2]),
        "period_current": parse_number(values[3]),
        "period_previous_year": parse_number(values[4]),
        "period_change_pct": parse_pct(values[5])
    }

In [19]:
parse_rgya_line(
    "3 हैदराबाद HYDERABAD (GHIAL) "
    "452164 464341 -2.6% "
    "2117531 2261073 -6.3%"
)

{'month_current': 452164.0,
 'month_previous_year': 464341.0,
 'month_change_pct': -2.6,
 'period_current': 2117531.0,
 'period_previous_year': 2261073.0,
 'period_change_pct': -6.3}

In [20]:
def extract_rgia_metric(pdf_bytes, metric_name, report_month):
    """
    Extract International, Domestic, and Combined RGIA records
    from an AAI traffic annexure PDF.
    """

    pages = extract_pdf_text(pdf_bytes)

    traffic_type_by_page = {
        1: "International",
        2: "Domestic",
        5: "Combined"
    }

    rows = []

    for page_no, traffic_type in traffic_type_by_page.items():

        page_text = pages[page_no - 1]

        for line in page_text.splitlines():

            if "HYDERABAD" in line.upper() and "GHIAL" in line.upper():

                parsed = parse_rgya_line(line)

                if parsed is not None:

                    rows.append({
                        "report_month": report_month,
                        "airport": "HYDERABAD (GHIAL)",
                        "metric": metric_name,
                        "traffic_type": traffic_type,
                        **parsed
                    })

    return pd.DataFrame(rows)

In [21]:
passenger_df = extract_rgia_metric(
    pdf_response.content,
    "Passengers",
    "2026-08"
)

movement_df = extract_rgia_metric(
    movement_response.content,
    "Aircraft Movements",
    "2026-08"
)

freight_df = extract_rgia_metric(
    freight_response.content,
    "Freight",
    "2026-08"
)

august_rgia = pd.concat(
    [passenger_df, movement_df, freight_df],
    ignore_index=True
)

august_rgia

,report_month,airport,metric,traffic_type,month_current,month_previous_year,month_change_pct,period_current,period_previous_year,period_change_pct
0,2026-08,HYDERABAD (GHIAL),Passengers,International,452164.0,464341.0,-2.6,2117531.0,2261073.0,-6.3
1,2026-08,HYDERABAD (GHIAL),Passengers,Domestic,1733770.0,2005921.0,-13.6,9379416.0,10734561.0,-12.6
2,2026-08,HYDERABAD (GHIAL),Passengers,Combined,2185934.0,2470262.0,-11.5,11496947.0,12995634.0,-11.5
3,2026-08,HYDERABAD (GHIAL),Aircraft Movements,International,2730.0,2834.0,-3.7,12504.0,13545.0,-7.7
4,2026-08,HYDERABAD (GHIAL),Aircraft Movements,Domestic,12082.0,14411.0,-16.2,65163.0,76564.0,-14.9
5,2026-08,HYDERABAD (GHIAL),Aircraft Movements,Combined,14812.0,17245.0,-14.1,77667.0,90109.0,-13.8
6,2026-08,HYDERABAD (GHIAL),Freight,International,11640.6,8725.1,33.4,56520.2,41546.7,36.0
7,2026-08,HYDERABAD (GHIAL),Freight,Domestic,5848.5,6232.5,-6.2,29719.7,30580.9,-2.8
8,2026-08,HYDERABAD (GHIAL),Freight,Combined,17489.1,14957.6,16.9,86240.0,72127.6,19.6

In [22]:
print("Rows:", len(august_rgia))
print("Columns:", len(august_rgia.columns))

print("\nMetrics:")
print(august_rgia["metric"].value_counts())

print("\nTraffic types:")
print(august_rgia["traffic_type"].value_counts())

print("\nDuplicates:")
print(
    august_rgia.duplicated(
        subset=["report_month", "metric", "traffic_type"]
    ).sum()
)

Rows: 9
Columns: 10

Metrics:
metric
Passengers            3
Aircraft Movements    3
Freight               3
Name: count, dtype: int64

Traffic types:
traffic_type
International    3
Domestic         3
Combined         3
Name: count, dtype: int64

Duplicates:
0

In [23]:
def validate_rgia_month(df):
    """
    Validate RGIA monthly totals against
    International + Domestic components.
    """

    results = []

    for metric in df["metric"].unique():

        metric_df = df[df["metric"] == metric]

        international = metric_df.loc[
            metric_df["traffic_type"] == "International",
            "month_current"
        ].iloc[0]

        domestic = metric_df.loc[
            metric_df["traffic_type"] == "Domestic",
            "month_current"
        ].iloc[0]

        combined = metric_df.loc[
            metric_df["traffic_type"] == "Combined",
            "month_current"
        ].iloc[0]

        calculated_total = international + domestic
        difference = combined - calculated_total

        results.append({
            "metric": metric,
            "international": international,
            "domestic": domestic,
            "reported_combined": combined,
            "calculated_combined": calculated_total,
            "difference": difference
        })

    return pd.DataFrame(results)


reconciliation = validate_rgia_month(august_rgia)

reconciliation

,metric,international,domestic,reported_combined,calculated_combined,difference
0,Passengers,452164.0,1733770.0,2185934.0,2185934.0,0.0
1,Aircraft Movements,2730.0,12082.0,14812.0,14812.0,0.0
2,Freight,11640.6,5848.5,17489.1,17489.1,0.0

In [24]:
def calculate_yoy(current, previous):
    if previous == 0:
        return np.nan

    return ((current - previous) / previous) * 100


august_rgia["calculated_month_change_pct"] = august_rgia.apply(
    lambda row: calculate_yoy(
        row["month_current"],
        row["month_previous_year"]
    ),
    axis=1
)

august_rgia["pct_difference"] = (
    august_rgia["calculated_month_change_pct"]
    - august_rgia["month_change_pct"]
)

august_rgia[
    [
        "metric",
        "traffic_type",
        "month_change_pct",
        "calculated_month_change_pct",
        "pct_difference"
    ]
]

,metric,traffic_type,month_change_pct,calculated_month_change_pct,pct_difference
0,Passengers,International,-2.6,-2.622426,-0.022426
1,Passengers,Domestic,-13.6,-13.567384,0.032616
2,Passengers,Combined,-11.5,-11.510034,-0.010034
3,Aircraft Movements,International,-3.7,-3.669725,0.030275
4,Aircraft Movements,Domestic,-16.2,-16.161266,0.038734
5,Aircraft Movements,Combined,-14.1,-14.108437,-0.008437
6,Freight,International,33.4,33.415090,0.015090
7,Freight,Domestic,-6.2,-6.161252,0.038748
8,Freight,Combined,16.9,16.924507,0.024507

In [25]:
# Inspecting AAI traffic-report PDF links

pdf_links = []

for link in soup.find_all("a"):
    href = link.get("href")
    text = link.get_text(" ", strip=True)

    if href and ".pdf" in href.lower():
        if href.startswith("/"):
            href = "https://www.aai.aero" + href

        pdf_links.append({
            "text": text,
            "url": href
        })

pdf_links_df = pd.DataFrame(pdf_links)

print("Total PDF links found:", len(pdf_links_df))

pdf_links_df.head(30)

Total PDF links found: 114

,text,url
0,Corporate Plan,https://www.aai.aero/sites/default/files/AAI_C...
1,Corporate Plan,https://www.aai.aero/sites/default/files/AAI_C...
2,Traffic News Summary,https://www.aai.aero/sites/default/files/traff...
3,Traffic News Summary,https://www.aai.aero/sites/default/files/traff...
4,Annexure-I-Airport Category wise Traffic Summary,https://www.aai.aero/sites/default/files/traff...
5,Annexure-I-Airport Category wise Traffic Summary,https://www.aai.aero/sites/default/files/traff...
6,Annexure-II-Aircraft Movement,https://www.aai.aero/sites/default/files/traff...
7,Annexure-II-Aircraft Movement,https://www.aai.aero/sites/default/files/traff...
8,Annexure-III-Passengers,https://www.aai.aero/sites/default/files/traff...
9,Annexure-III-Passengers,https://www.aai.aero/sites/default/files/traff...
10,Annexure-IV-Freight,https://www.aai.aero/sites/default/files/traff...
11,Annexure-IV-Freight,https://www.aai.aero/sites/default/files/traff...
12,Annexure-V-Region Wise Trends and Share in Air...,https://www.aai.aero/sites/default/files/traff...
13,Annexure-V-Region Wise Trends and Share in Air...,https://www.aai.aero/sites/default/files/traff...
14,Annexure-VI-State/ Union Territory Traffic,https://www.aai.aero/sites/default/files/traff...
15,Annexure-VI-State/ Union Territory Traffic,https://www.aai.aero/sites/default/files/traff...
16,Traffic News Summary,https://www.aai.aero/sites/default/files/traff...
17,Traffic News Summary,https://www.aai.aero/sites/default/files/traff...
18,Annexure-I-Airport Category wise Traffic Summary,https://www.aai.aero/sites/default/files/traff...
19,Annexure-I-Airport Category wise Traffic Summary,https://www.aai.aero/sites/default/files/traff...
20,Annexure-II-Aircraft Movement,https://www.aai.aero/sites/default/files/traff...
21,Annexure-II-Aircraft Movement,https://www.aai.aero/sites/default/files/traff...
22,Annexure-III-Passengers,https://www.aai.aero/sites/default/files/traff...
23,Annexure-III-Passengers,https://www.aai.aero/sites/default/files/traff...
24,Annexure-IV-Freight,https://www.aai.aero/sites/default/files/traff...
25,Annexure-IV-Freight,https://www.aai.aero/sites/default/files/traff...
26,Annexure-V-Region Wise Trends and Share in Air...,https://www.aai.aero/sites/default/files/traff...
27,Annexure-V-Region Wise Trends and Share in Air...,https://www.aai.aero/sites/default/files/traff...
28,Annexure-VI-State/ Union Territory Traffic,https://www.aai.aero/sites/default/files/traff...
29,Annexure-VI-State/ Union Territory Traffic,https://www.aai.aero/sites/default/files/traff...

In [26]:
# Show PDF filenames so we can inspect AAI's naming pattern

pdf_links_df["filename"] = pdf_links_df["url"].str.split("/").str[-1]

pdf_links_df[
    ["text", "filename", "url"]
].drop_duplicates().head(50)

,text,filename,url
0,Corporate Plan,AAI_CORPORATE_PLAN_2017-26_with_revised_vision...,https://www.aai.aero/sites/default/files/AAI_C...
2,Traffic News Summary,TRAug2k26.pdf,https://www.aai.aero/sites/default/files/traff...
4,Annexure-I-Airport Category wise Traffic Summary,Aug2k26Annex1.pdf,https://www.aai.aero/sites/default/files/traff...
6,Annexure-II-Aircraft Movement,Aug2k26Annex2.pdf,https://www.aai.aero/sites/default/files/traff...
8,Annexure-III-Passengers,Aug2k26Annex3.pdf,https://www.aai.aero/sites/default/files/traff...
10,Annexure-IV-Freight,Aug2k26Annex_4.pdf,https://www.aai.aero/sites/default/files/traff...
12,Annexure-V-Region Wise Trends and Share in Air...,Aug2k26Annex5.pdf,https://www.aai.aero/sites/default/files/traff...
14,Annexure-VI-State/ Union Territory Traffic,Aug2k26Annex6.pdf,https://www.aai.aero/sites/default/files/traff...
16,Traffic News Summary,TRjul2k26.pdf,https://www.aai.aero/sites/default/files/traff...
18,Annexure-I-Airport Category wise Traffic Summary,Jul2k26Annex1.pdf,https://www.aai.aero/sites/default/files/traff...
20,Annexure-II-Aircraft Movement,Jul2k26Annex2.pdf,https://www.aai.aero/sites/default/files/traff...
22,Annexure-III-Passengers,Jul2k26Annex3.pdf,https://www.aai.aero/sites/default/files/traff...
24,Annexure-IV-Freight,Jul2k26Annex4.pdf,https://www.aai.aero/sites/default/files/traff...
26,Annexure-V-Region Wise Trends and Share in Air...,Jul2k26Annex5.pdf,https://www.aai.aero/sites/default/files/traff...
28,Annexure-VI-State/ Union Territory Traffic,Jul2k26Annex6.pdf,https://www.aai.aero/sites/default/files/traff...
30,Traffic News Summary,TRJun2k26.pdf,https://www.aai.aero/sites/default/files/traff...
32,Annexure-I-Airport Category wise Traffic Summary,Jun2k26Annex1.pdf,https://www.aai.aero/sites/default/files/traff...
34,Annexure-II-Aircraft Movement,Jun2k26Annex2.pdf,https://www.aai.aero/sites/default/files/traff...
36,Annexure-III-Passengers,Jun2k26Annex3.pdf,https://www.aai.aero/sites/default/files/traff...
38,Annexure-IV-Freight,Jun2k26Annex4.pdf,https://www.aai.aero/sites/default/files/traff...
40,Annexure-V-Region Wise Trends and Share in Air...,Jun2k26Annex5.pdf,https://www.aai.aero/sites/default/files/traff...
42,Annexure-VI-State/ Union Territory Traffic,Jun2k26Annex6.pdf,https://www.aai.aero/sites/default/files/traff...
44,Traffic News Summary,TRMay2k26.pdf,https://www.aai.aero/sites/default/files/traff...
46,Annexure-I-Airport Category wise Traffic Summary,May2k26Annex1.pdf,https://www.aai.aero/sites/default/files/traff...
48,Annexure-II-Aircraft Movement,May2k26Annex2.pdf,https://www.aai.aero/sites/default/files/traff...
50,Annexure-III-Passengers,May2K26Annex3.pdf,https://www.aai.aero/sites/default/files/traff...
52,Annexure-IV-Freight,May2k26Annex4.pdf,https://www.aai.aero/sites/default/files/traff...
54,Annexure-V-Region Wise Trends and Share in Air...,May2k26Annex5.pdf,https://www.aai.aero/sites/default/files/traff...
56,Annexure-VI-State/ Union Territory Traffic,May2k26Annex6_0.pdf,https://www.aai.aero/sites/default/files/traff...
58,Traffic News Summary,TRApr2k26.pdf,https://www.aai.aero/sites/default/files/traff...
60,Annexure-I-Airport Category wise Traffic Summary,April2k26Annex1.pdf,https://www.aai.aero/sites/default/files/traff...
62,Annexure-II-Aircraft Movement,April2k26Annex2.pdf,https://www.aai.aero/sites/default/files/traff...
64,Annexure-III-Passengers,April2k26Annex3.pdf,https://www.aai.aero/sites/default/files/traff...
66,Annexure-IV-Freight,April2k26Annex4.pdf,https://www.aai.aero/sites/default/files/traff...
68,Annexure-V-Region Wise Trends and Share in Air...,April2k26Anex5.pdf,https://www.aai.aero/sites/default/files/traff...
70,Annexure-VI-State/ Union Territory Traffic,April2k26Annex6.pdf,https://www.aai.aero/sites/default/files/traff...
72,Traffic News Summary,TRMar2k26_2.pdf,https://www.aai.aero/sites/default/files/traff...
74,Annexure-I-Airport Category wise Traffic Summary,Mar2k26Annex1_0.pdf,https://www.aai.aero/sites/default/files/traff...
76,Annexure-II-Aircraft Movement,Mar2k26Annex2_0.pdf,https://www.aai.aero/sites/default/files/traff...
78,Annexure-III-Passengers,Mar2k26Annex3_0.pdf,https://www.aai.aero/sites/default/files/traff...
80,Annexure-IV-Freight,Mar2k26Annex4.pdf,https://www.aai.aero/sites/default/files/traff...
82,Annexure-V-Region Wise Trends and Share in Air...,Mar2k26Annex5.pdf,https://www.aai.aero/sites/default/files/traff...
84,Annexure-VI-State/ Union Territory Traffic,Mar2k26Annex6.pdf,https://www.aai.aero/sites/default/files/traff...
86,Traffic News Summary,TRFeb2k26.pdf,https://www.aai.aero/sites/default/files/traff...
88,Annexure-I-Airport Category wise Traffic Summary,Feb2k26Annex1.pdf,https://www.aai.aero/sites/default/files/traff...
90,Annexure-II-Aircraft Movement,Feb2k26Annex2.pdf,https://www.aai.aero/sites/default/files/traff...
92,Annexure-III-Passengers,Feb2k26Annex3.pdf,https://www.aai.aero/sites/default/files/traff...
94,Annexure-IV-Freight,Feb2k26Annex4.pdf,https://www.aai.aero/sites/default/files/traff...
96,Annexure-V-Region Wise Trends and Share in Air...,Feb2k26Annex5.pdf,https://www.aai.aero/sites/default/files/traff...
98,Annexure-VI-State/ Union Territory Traffic,Feb2k26Annex6.pdf,https://www.aai.aero/sites/default/files/traff...

In [27]:
# Keep only the three annexures required for our project

required_annexures = {
    "Annexure-II-Aircraft Movement": "Aircraft Movements",
    "Annexure-III-Passengers": "Passengers",
    "Annexure-IV-Freight": "Freight"
}

traffic_links = []

for _, row in pdf_links_df.iterrows():

    text = row["text"].strip()

    for source_name, metric_name in required_annexures.items():

        if source_name.lower() in text.lower():

            traffic_links.append({
                "source_text": text,
                "metric": metric_name,
                "url": row["url"],
                "filename": row["filename"]
            })

traffic_links_df = pd.DataFrame(traffic_links)

traffic_links_df = traffic_links_df.drop_duplicates(
    subset=["metric", "url"]
).reset_index(drop=True)

print("Total required PDF links:", len(traffic_links_df))

traffic_links_df.head(30)

Total required PDF links: 24

,source_text,metric,url,filename
0,Annexure-II-Aircraft Movement,Aircraft Movements,https://www.aai.aero/sites/default/files/traff...,Aug2k26Annex2.pdf
1,Annexure-III-Passengers,Passengers,https://www.aai.aero/sites/default/files/traff...,Aug2k26Annex3.pdf
2,Annexure-IV-Freight,Freight,https://www.aai.aero/sites/default/files/traff...,Aug2k26Annex_4.pdf
3,Annexure-II-Aircraft Movement,Aircraft Movements,https://www.aai.aero/sites/default/files/traff...,Jul2k26Annex2.pdf
4,Annexure-III-Passengers,Passengers,https://www.aai.aero/sites/default/files/traff...,Jul2k26Annex3.pdf
5,Annexure-IV-Freight,Freight,https://www.aai.aero/sites/default/files/traff...,Jul2k26Annex4.pdf
6,Annexure-II-Aircraft Movement,Aircraft Movements,https://www.aai.aero/sites/default/files/traff...,Jun2k26Annex2.pdf
7,Annexure-III-Passengers,Passengers,https://www.aai.aero/sites/default/files/traff...,Jun2k26Annex3.pdf
8,Annexure-IV-Freight,Freight,https://www.aai.aero/sites/default/files/traff...,Jun2k26Annex4.pdf
9,Annexure-II-Aircraft Movement,Aircraft Movements,https://www.aai.aero/sites/default/files/traff...,May2k26Annex2.pdf
10,Annexure-III-Passengers,Passengers,https://www.aai.aero/sites/default/files/traff...,May2K26Annex3.pdf
11,Annexure-IV-Freight,Freight,https://www.aai.aero/sites/default/files/traff...,May2k26Annex4.pdf
12,Annexure-II-Aircraft Movement,Aircraft Movements,https://www.aai.aero/sites/default/files/traff...,April2k26Annex2.pdf
13,Annexure-III-Passengers,Passengers,https://www.aai.aero/sites/default/files/traff...,April2k26Annex3.pdf
14,Annexure-IV-Freight,Freight,https://www.aai.aero/sites/default/files/traff...,April2k26Annex4.pdf
15,Annexure-II-Aircraft Movement,Aircraft Movements,https://www.aai.aero/sites/default/files/traff...,Mar2k26Annex2_0.pdf
16,Annexure-III-Passengers,Passengers,https://www.aai.aero/sites/default/files/traff...,Mar2k26Annex3_0.pdf
17,Annexure-IV-Freight,Freight,https://www.aai.aero/sites/default/files/traff...,Mar2k26Annex4.pdf
18,Annexure-II-Aircraft Movement,Aircraft Movements,https://www.aai.aero/sites/default/files/traff...,Feb2k26Annex2.pdf
19,Annexure-III-Passengers,Passengers,https://www.aai.aero/sites/default/files/traff...,Feb2k26Annex3.pdf
20,Annexure-IV-Freight,Freight,https://www.aai.aero/sites/default/files/traff...,Feb2k26Annex4.pdf
21,Annexure-II-Aircraft Movement,Aircraft Movements,https://www.aai.aero/sites/default/files/traff...,Jan2k26Annex2_0.pdf
22,Annexure-III-Passengers,Passengers,https://www.aai.aero/sites/default/files/traff...,Jan2k26Annex3_0.pdf
23,Annexure-IV-Freight,Freight,https://www.aai.aero/sites/default/files/traff...,Jan2k26Annex4_0.pdf

In [28]:
# Inspect the number of reports available for each metric

traffic_links_df.groupby("metric").size()

metric
Aircraft Movements    8
Freight               8
Passengers            8
dtype: int64

In [29]:
# Display the discovered filenames in chronological-page order

traffic_links_df[
    ["metric", "filename", "url"]
].to_string(index=False)

'            metric            filename                                                                       url\nAircraft Movements   Aug2k26Annex2.pdf   https://www.aai.aero/sites/default/files/traffic-news/Aug2k26Annex2.pdf\n        Passengers   Aug2k26Annex3.pdf   https://www.aai.aero/sites/default/files/traffic-news/Aug2k26Annex3.pdf\n           Freight  Aug2k26Annex_4.pdf  https://www.aai.aero/sites/default/files/traffic-news/Aug2k26Annex_4.pdf\nAircraft Movements   Jul2k26Annex2.pdf   https://www.aai.aero/sites/default/files/traffic-news/Jul2k26Annex2.pdf\n        Passengers   Jul2k26Annex3.pdf   https://www.aai.aero/sites/default/files/traffic-news/Jul2k26Annex3.pdf\n           Freight   Jul2k26Annex4.pdf   https://www.aai.aero/sites/default/files/traffic-news/Jul2k26Annex4.pdf\nAircraft Movements   Jun2k26Annex2.pdf   https://www.aai.aero/sites/default/files/traffic-news/Jun2k26Annex2.pdf\n        Passengers   Jun2k26Annex3.pdf   https://www.aai.aero/sites/default/files/traffic-news/Jun2k26Annex3.pdf\n           Freight   Jun2k26Annex4.pdf   https://www.aai.aero/sites/default/files/traffic-news/Jun2k26Annex4.pdf\nAircraft Movements   May2k26Annex2.pdf   https://www.aai.aero/sites/default/files/traffic-news/May2k26Annex2.pdf\n        Passengers   May2K26Annex3.pdf   https://www.aai.aero/sites/default/files/traffic-news/May2K26Annex3.pdf\n           Freight   May2k26Annex4.pdf   https://www.aai.aero/sites/default/files/traffic-news/May2k26Annex4.pdf\nAircraft Movements April2k26Annex2.pdf https://www.aai.aero/sites/default/files/traffic-news/April2k26Annex2.pdf\n        Passengers April2k26Annex3.pdf https://www.aai.aero/sites/default/files/traffic-news/April2k26Annex3.pdf\n           Freight April2k26Annex4.pdf https://www.aai.aero/sites/default/files/traffic-news/April2k26Annex4.pdf\nAircraft Movements Mar2k26Annex2_0.pdf https://www.aai.aero/sites/default/files/traffic-news/Mar2k26Annex2_0.pdf\n        Passengers Mar2k26Annex3_0.pdf https://www.aai.aero/sites/default/files/traffic-news/Mar2k26Annex3_0.pdf\n           Freight   Mar2k26Annex4.pdf   https://www.aai.aero/sites/default/files/traffic-news/Mar2k26Annex4.pdf\nAircraft Movements   Feb2k26Annex2.pdf   https://www.aai.aero/sites/default/files/traffic-news/Feb2k26Annex2.pdf\n        Passengers   Feb2k26Annex3.pdf   https://www.aai.aero/sites/default/files/traffic-news/Feb2k26Annex3.pdf\n           Freight   Feb2k26Annex4.pdf   https://www.aai.aero/sites/default/files/traffic-news/Feb2k26Annex4.pdf\nAircraft Movements Jan2k26Annex2_0.pdf https://www.aai.aero/sites/default/files/traffic-news/Jan2k26Annex2_0.pdf\n        Passengers Jan2k26Annex3_0.pdf https://www.aai.aero/sites/default/files/traffic-news/Jan2k26Annex3_0.pdf\n           Freight Jan2k26Annex4_0.pdf https://www.aai.aero/sites/default/files/traffic-news/Jan2k26Annex4_0.pdf'

In [30]:

# AAI TRAFFIC REPORT INVENTORY\
inventory = (
    traffic_links_df
    .groupby(["metric"])
    .size()
    .reset_index(name="pdf_count")
)

print("PDF INVENTORY")
print("=" * 50)
print(inventory.to_string(index=False))

print("\n\nUNIQUE PDF URLs:", traffic_links_df["url"].nunique())

print("\n\nFIRST 10 REPORTS")
print("=" * 50)

print(
    traffic_links_df[
        ["metric", "filename"]
    ].head(10).to_string(index=False)
)

print("\n\nLAST 10 REPORTS")
print("=" * 50)

print(
    traffic_links_df[
        ["metric", "filename"]
    ].tail(10).to_string(index=False)
)

PDF INVENTORY
==================================================
            metric  pdf_count
Aircraft Movements          8
           Freight          8
        Passengers          8


UNIQUE PDF URLs: 24


FIRST 10 REPORTS
==================================================
            metric           filename
Aircraft Movements  Aug2k26Annex2.pdf
        Passengers  Aug2k26Annex3.pdf
           Freight Aug2k26Annex_4.pdf
Aircraft Movements  Jul2k26Annex2.pdf
        Passengers  Jul2k26Annex3.pdf
           Freight  Jul2k26Annex4.pdf
Aircraft Movements  Jun2k26Annex2.pdf
        Passengers  Jun2k26Annex3.pdf
           Freight  Jun2k26Annex4.pdf
Aircraft Movements  May2k26Annex2.pdf


LAST 10 REPORTS
==================================================
            metric            filename
           Freight April2k26Annex4.pdf
Aircraft Movements Mar2k26Annex2_0.pdf
        Passengers Mar2k26Annex3_0.pdf
           Freight   Mar2k26Annex4.pdf
Aircraft Movements   Feb2k26Annex2.pdf
        Passengers   Feb2k26Annex3.pdf
           Freight   Feb2k26Annex4.pdf
Aircraft Movements Jan2k26Annex2_0.pdf
        Passengers Jan2k26Annex3_0.pdf
           Freight Jan2k26Annex4_0.pdf

In [32]:
metric_counts = traffic_links_df.groupby("metric").size()

print(metric_counts)

if metric_counts.nunique() == 1:
    print("\n✅ All three metrics have the same number of discovered reports.")
else:
    print("\n⚠️ Metrics have different numbers of reports.")

metric
Aircraft Movements    8
Freight               8
Passengers            8
dtype: int64

✅ All three metrics have the same number of discovered reports.

In [33]:


duplicate_count = traffic_links_df.duplicated(
    subset=["metric", "url"]
).sum()

print("Duplicate metric + URL records:", duplicate_count)

Duplicate metric + URL records: 0

In [34]:


for metric in ["Passengers", "Aircraft Movements", "Freight"]:

    print(f"\n{'=' * 60}")
    print(metric.upper())
    print(f"{'=' * 60}")

    metric_files = traffic_links_df[
        traffic_links_df["metric"] == metric
    ]

    for filename in metric_files["filename"]:
        print(filename)

============================================================
PASSENGERS
============================================================
Aug2k26Annex3.pdf
Jul2k26Annex3.pdf
Jun2k26Annex3.pdf
May2K26Annex3.pdf
April2k26Annex3.pdf
Mar2k26Annex3_0.pdf
Feb2k26Annex3.pdf
Jan2k26Annex3_0.pdf

============================================================
AIRCRAFT MOVEMENTS
============================================================
Aug2k26Annex2.pdf
Jul2k26Annex2.pdf
Jun2k26Annex2.pdf
May2k26Annex2.pdf
April2k26Annex2.pdf
Mar2k26Annex2_0.pdf
Feb2k26Annex2.pdf
Jan2k26Annex2_0.pdf

============================================================
FREIGHT
============================================================
Aug2k26Annex_4.pdf
Jul2k26Annex4.pdf
Jun2k26Annex4.pdf
May2k26Annex4.pdf
April2k26Annex4.pdf
Mar2k26Annex4.pdf
Feb2k26Annex4.pdf
Jan2k26Annex4_0.pdf

In [35]:


print(
    traffic_links_df[
        ["metric", "filename"]
    ].to_string(index=False)
)

            metric            filename
Aircraft Movements   Aug2k26Annex2.pdf
        Passengers   Aug2k26Annex3.pdf
           Freight  Aug2k26Annex_4.pdf
Aircraft Movements   Jul2k26Annex2.pdf
        Passengers   Jul2k26Annex3.pdf
           Freight   Jul2k26Annex4.pdf
Aircraft Movements   Jun2k26Annex2.pdf
        Passengers   Jun2k26Annex3.pdf
           Freight   Jun2k26Annex4.pdf
Aircraft Movements   May2k26Annex2.pdf
        Passengers   May2K26Annex3.pdf
           Freight   May2k26Annex4.pdf
Aircraft Movements April2k26Annex2.pdf
        Passengers April2k26Annex3.pdf
           Freight April2k26Annex4.pdf
Aircraft Movements Mar2k26Annex2_0.pdf
        Passengers Mar2k26Annex3_0.pdf
           Freight   Mar2k26Annex4.pdf
Aircraft Movements   Feb2k26Annex2.pdf
        Passengers   Feb2k26Annex3.pdf
           Freight   Feb2k26Annex4.pdf
Aircraft Movements Jan2k26Annex2_0.pdf
        Passengers Jan2k26Annex3_0.pdf
           Freight Jan2k26Annex4_0.pdf

In [36]:

#AAI REPORT MANIFEST

month_map = {
    "Jan": "2026-01",
    "Feb": "2026-02",
    "Mar": "2026-03",
    "April": "2026-04",
    "May": "2026-05",
    "Jun": "2026-06",
    "Jul": "2026-07",
    "Aug": "2026-08"
}

def identify_report_month(filename):
    filename_lower = filename.lower()

    for month_name, month_value in month_map.items():

        if month_name.lower() in filename_lower:
            return month_value

    return None


manifest = traffic_links_df.copy()

manifest["report_month"] = manifest["filename"].apply(
    identify_report_month
)

manifest = manifest[
    [
        "report_month",
        "metric",
        "filename",
        "url"
    ]
].rename(
    columns={"url": "source_url"}
)

manifest = manifest.sort_values(
    ["report_month", "metric"]
).reset_index(drop=True)

print(manifest.to_string(index=False))

report_month             metric            filename                                                                source_url
     2026-01 Aircraft Movements Jan2k26Annex2_0.pdf https://www.aai.aero/sites/default/files/traffic-news/Jan2k26Annex2_0.pdf
     2026-01            Freight Jan2k26Annex4_0.pdf https://www.aai.aero/sites/default/files/traffic-news/Jan2k26Annex4_0.pdf
     2026-01         Passengers Jan2k26Annex3_0.pdf https://www.aai.aero/sites/default/files/traffic-news/Jan2k26Annex3_0.pdf
     2026-02 Aircraft Movements   Feb2k26Annex2.pdf   https://www.aai.aero/sites/default/files/traffic-news/Feb2k26Annex2.pdf
     2026-02            Freight   Feb2k26Annex4.pdf   https://www.aai.aero/sites/default/files/traffic-news/Feb2k26Annex4.pdf
     2026-02         Passengers   Feb2k26Annex3.pdf   https://www.aai.aero/sites/default/files/traffic-news/Feb2k26Annex3.pdf
     2026-03 Aircraft Movements Mar2k26Annex2_0.pdf https://www.aai.aero/sites/default/files/traffic-news/Mar2k26Annex2_0.pdf
     2026-03            Freight   Mar2k26Annex4.pdf   https://www.aai.aero/sites/default/files/traffic-news/Mar2k26Annex4.pdf
     2026-03         Passengers Mar2k26Annex3_0.pdf https://www.aai.aero/sites/default/files/traffic-news/Mar2k26Annex3_0.pdf
     2026-04 Aircraft Movements April2k26Annex2.pdf https://www.aai.aero/sites/default/files/traffic-news/April2k26Annex2.pdf
     2026-04            Freight April2k26Annex4.pdf https://www.aai.aero/sites/default/files/traffic-news/April2k26Annex4.pdf
     2026-04         Passengers April2k26Annex3.pdf https://www.aai.aero/sites/default/files/traffic-news/April2k26Annex3.pdf
     2026-05 Aircraft Movements   May2k26Annex2.pdf   https://www.aai.aero/sites/default/files/traffic-news/May2k26Annex2.pdf
     2026-05            Freight   May2k26Annex4.pdf   https://www.aai.aero/sites/default/files/traffic-news/May2k26Annex4.pdf
     2026-05         Passengers   May2K26Annex3.pdf   https://www.aai.aero/sites/default/files/traffic-news/May2K26Annex3.pdf
     2026-06 Aircraft Movements   Jun2k26Annex2.pdf   https://www.aai.aero/sites/default/files/traffic-news/Jun2k26Annex2.pdf
     2026-06            Freight   Jun2k26Annex4.pdf   https://www.aai.aero/sites/default/files/traffic-news/Jun2k26Annex4.pdf
     2026-06         Passengers   Jun2k26Annex3.pdf   https://www.aai.aero/sites/default/files/traffic-news/Jun2k26Annex3.pdf
     2026-07 Aircraft Movements   Jul2k26Annex2.pdf   https://www.aai.aero/sites/default/files/traffic-news/Jul2k26Annex2.pdf
     2026-07            Freight   Jul2k26Annex4.pdf   https://www.aai.aero/sites/default/files/traffic-news/Jul2k26Annex4.pdf
     2026-07         Passengers   Jul2k26Annex3.pdf   https://www.aai.aero/sites/default/files/traffic-news/Jul2k26Annex3.pdf
     2026-08 Aircraft Movements   Aug2k26Annex2.pdf   https://www.aai.aero/sites/default/files/traffic-news/Aug2k26Annex2.pdf
     2026-08            Freight  Aug2k26Annex_4.pdf  https://www.aai.aero/sites/default/files/traffic-news/Aug2k26Annex_4.pdf
     2026-08         Passengers   Aug2k26Annex3.pdf   https://www.aai.aero/sites/default/files/traffic-news/Aug2k26Annex3.pdf

In [37]:
# Manifest validation

print("Total records:", len(manifest))
print("Unique months:", manifest["report_month"].nunique())
print("Unique URLs:", manifest["source_url"].nunique())
print("Missing months:", manifest["report_month"].isna().sum())
print("Duplicate records:", manifest.duplicated().sum())

print("\nReports per month:")
print(manifest.groupby("report_month").size())

Total records: 24
Unique months: 8
Unique URLs: 24
Missing months: 0
Duplicate records: 0

Reports per month:
report_month
2026-01    3
2026-02    3
2026-03    3
2026-04    3
2026-05    3
2026-06    3
2026-07    3
2026-08    3
dtype: int64

In [38]:

#PROJECT DATA DIRECTORIES

RAW_DIR = "/content/rgia_airport_analytics/data/raw"
PROCESSED_DIR = "/content/rgia_airport_analytics/data/processed"

os.makedirs(RAW_DIR, exist_ok=True)
os.makedirs(PROCESSED_DIR, exist_ok=True)

print("Raw directory:", RAW_DIR)
print("Processed directory:", PROCESSED_DIR)

Raw directory: /content/rgia_airport_analytics/data/raw
Processed directory: /content/rgia_airport_analytics/data/processed

In [39]:


download_log = []

for _, row in manifest.iterrows():

    report_month = row["report_month"]
    metric = row["metric"]
    filename = row["filename"]
    url = row["source_url"]

    metric_folder = metric.lower().replace(" ", "_")

    folder = os.path.join(
        RAW_DIR,
        metric_folder
    )

    os.makedirs(folder, exist_ok=True)

    filepath = os.path.join(folder, filename)

    try:

        r = requests.get(
            url,
            headers={"User-Agent": "Mozilla/5.0"},
            timeout=60
        )

        r.raise_for_status()

        with open(filepath, "wb") as f:
            f.write(r.content)

        download_log.append({
            "report_month": report_month,
            "metric": metric,
            "filename": filename,
            "status": "Downloaded",
            "size_kb": round(len(r.content) / 1024, 2),
            "filepath": filepath
        })

    except Exception as e:

        download_log.append({
            "report_month": report_month,
            "metric": metric,
            "filename": filename,
            "status": f"ERROR: {e}",
            "size_kb": None,
            "filepath": filepath
        })


download_log_df = pd.DataFrame(download_log)

download_log_df

,report_month,metric,filename,status,size_kb,filepath
0,2026-01,Aircraft Movements,Jan2k26Annex2_0.pdf,Downloaded,1045.75,/content/rgia_airport_analytics/data/raw/aircr...
1,2026-01,Freight,Jan2k26Annex4_0.pdf,Downloaded,1038.77,/content/rgia_airport_analytics/data/raw/freig...
2,2026-01,Passengers,Jan2k26Annex3_0.pdf,Downloaded,1072.56,/content/rgia_airport_analytics/data/raw/passe...
3,2026-02,Aircraft Movements,Feb2k26Annex2.pdf,Downloaded,486.50,/content/rgia_airport_analytics/data/raw/aircr...
4,2026-02,Freight,Feb2k26Annex4.pdf,Downloaded,480.13,/content/rgia_airport_analytics/data/raw/freig...
5,2026-02,Passengers,Feb2k26Annex3.pdf,Downloaded,488.21,/content/rgia_airport_analytics/data/raw/passe...
6,2026-03,Aircraft Movements,Mar2k26Annex2_0.pdf,Downloaded,477.75,/content/rgia_airport_analytics/data/raw/aircr...
7,2026-03,Freight,Mar2k26Annex4.pdf,Downloaded,471.38,/content/rgia_airport_analytics/data/raw/freig...
8,2026-03,Passengers,Mar2k26Annex3_0.pdf,Downloaded,479.68,/content/rgia_airport_analytics/data/raw/passe...
9,2026-04,Aircraft Movements,April2k26Annex2.pdf,Downloaded,479.25,/content/rgia_airport_analytics/data/raw/aircr...
10,2026-04,Freight,April2k26Annex4.pdf,Downloaded,438.24,/content/rgia_airport_analytics/data/raw/freig...
11,2026-04,Passengers,April2k26Annex3.pdf,Downloaded,474.64,/content/rgia_airport_analytics/data/raw/passe...
12,2026-05,Aircraft Movements,May2k26Annex2.pdf,Downloaded,485.86,/content/rgia_airport_analytics/data/raw/aircr...
13,2026-05,Freight,May2k26Annex4.pdf,Downloaded,483.62,/content/rgia_airport_analytics/data/raw/freig...
14,2026-05,Passengers,May2K26Annex3.pdf,Downloaded,485.20,/content/rgia_airport_analytics/data/raw/passe...
15,2026-06,Aircraft Movements,Jun2k26Annex2.pdf,Downloaded,1045.81,/content/rgia_airport_analytics/data/raw/aircr...
16,2026-06,Freight,Jun2k26Annex4.pdf,Downloaded,1040.05,/content/rgia_airport_analytics/data/raw/freig...
17,2026-06,Passengers,Jun2k26Annex3.pdf,Downloaded,1044.12,/content/rgia_airport_analytics/data/raw/passe...
18,2026-07,Aircraft Movements,Jul2k26Annex2.pdf,Downloaded,1048.76,/content/rgia_airport_analytics/data/raw/aircr...
19,2026-07,Freight,Jul2k26Annex4.pdf,Downloaded,1042.45,/content/rgia_airport_analytics/data/raw/freig...
20,2026-07,Passengers,Jul2k26Annex3.pdf,Downloaded,1046.91,/content/rgia_airport_analytics/data/raw/passe...
21,2026-08,Aircraft Movements,Aug2k26Annex2.pdf,Downloaded,490.25,/content/rgia_airport_analytics/data/raw/aircr...
22,2026-08,Freight,Aug2k26Annex_4.pdf,Downloaded,128.23,/content/rgia_airport_analytics/data/raw/freig...
23,2026-08,Passengers,Aug2k26Annex3.pdf,Downloaded,488.70,/content/rgia_airport_analytics/data/raw/passe...

In [40]:
print("Total downloads:", len(download_log_df))

print("\nStatus:")
print(download_log_df["status"].value_counts())

print("\nFailed downloads:")
print(
    download_log_df[
        download_log_df["status"] != "Downloaded"
    ][
        ["report_month", "metric", "filename", "status"]
    ]
)

Total downloads: 24

Status:
status
Downloaded    24
Name: count, dtype: int64

Failed downloads:
Empty DataFrame
Columns: [report_month, metric, filename, status]
Index: []

In [41]:


def inspect_rgia_pages(filepath):
    """
    Find pages containing the RGIA (HYDERABAD / GHIAL)
    record and display the matching lines.
    """

    with open(filepath, "rb") as f:
        pdf_bytes = f.read()

    pages = extract_pdf_text(pdf_bytes)

    results = []

    for page_no, page_text in enumerate(pages, start=1):

        for line in page_text.splitlines():

            if (
                "HYDERABAD" in line.upper()
                and "GHIAL" in line.upper()
            ):
                results.append({
                    "page": page_no,
                    "line": line.strip()
                })

    return pd.DataFrame(results)


# Test one report from each metric
test_files = manifest[
    (manifest["report_month"].isin([
        "2026-01",
        "2026-04",
        "2026-08"
    ]))
].copy()

for _, row in test_files.iterrows():

    metric_folder = row["metric"].lower().replace(" ", "_")

    filepath = os.path.join(
        RAW_DIR,
        metric_folder,
        row["filename"]
    )

    print("=" * 80)
    print("Month :", row["report_month"])
    print("Metric:", row["metric"])
    print("File  :", row["filename"])

    result = inspect_rgia_pages(filepath)

    print(result.to_string(index=False))
    print()

================================================================================
Month : 2026-01
Metric: Aircraft Movements
File  : Jan2k26Annex2_0.pdf
 page                                                              line
    1     3 हैदराबाद HYDERABAD (GHIAL) 2895 2522 14.8% 27535 25115 9.6%
    2 3 हैदराबाद HYDERABAD (GHIAL) 13999 15271 -8.3% 149557 141750 5.5%
    5 3 हैदराबाद HYDERABAD (GHIAL) 16894 17793 -5.1% 177092 166865 6.1%

================================================================================
Month : 2026-01
Metric: Freight
File  : Jan2k26Annex4_0.pdf
 page                                                                      line
    1    3 हैदराबाद HYDERABAD (GHIAL) 9311.5 7302.2 27.5% 90615.5 80941.4 12.0%
    2      3 हैदराबाद HYDERABAD (GHIAL) 5596.8 5487.2 2.0% 60536.5 57730.9 4.9%
    5 3 हैदराबाद HYDERABAD (GHIAL) 14908.4 12789.4 16.6% 151152.0 138672.3 9.0%

================================================================================
Month : 2026-01
Metric: Passengers
File  : Jan2k26Annex3_0.pdf
 page                                                                      line
    1    3 हैदराबाद HYDERABAD (GHIAL) 523439 424013 23.4% 4717724 3935053 19.9%
    2 3 हैदराबाद HYDERABAD (GHIAL) 2129340 2218574 -4.0% 21160774 20104882 5.3%
    5  3 हैदराबाद HYDERABAD (GHIAL) 2652779 2642587 0.4% 25878498 24039935 7.6%

================================================================================
Month : 2026-04
Metric: Aircraft Movements
File  : April2k26Annex2.pdf
 page                                                              line
    1     3हैदराबाद HYDERABAD (GHIAL) 2010 2590 -22.4% 2010 2590 -22.4%
    2 3हैदराबाद HYDERABAD (GHIAL) 13819 15695 -12.0% 13819 15695 -12.0%
    5 3हैदराबाद HYDERABAD (GHIAL) 15829 18285 -13.4% 15829 18285 -13.4%

================================================================================
Month : 2026-04
Metric: Freight
File  : April2k26Annex4.pdf
 page                                                                    line
    1   3हैदराबाद HYDERABAD (GHIAL) 10317.0 7676.1 34.4% 10317.0 7676.1 34.4%
    2     3हैदराबाद HYDERABAD (GHIAL) 5843.6 5974.2 -2.2% 5843.6 5974.2 -2.2%
    5 3हैदराबाद HYDERABAD (GHIAL) 16160.6 13650.3 18.4% 16160.6 13650.3 18.4%

================================================================================
Month : 2026-04
Metric: Passengers
File  : April2k26Annex3.pdf
 page                                                                      line
    1     3हैदराबाद HYDERABAD (GHIAL) 340896 423792 -19.6% 340896 423792 -19.6%
    2 3हैदराबाद HYDERABAD (GHIAL) 1909069 2225782 -14.2% 1909069 2225782 -14.2%
    5 3हैदराबाद HYDERABAD (GHIAL) 2249965 2649574 -15.1% 2249965 2649574 -15.1%

================================================================================
Month : 2026-08
Metric: Aircraft Movements
File  : Aug2k26Annex2.pdf
 page                                                               line
    1     3 हैदराबाद HYDERABAD (GHIAL) 2730 2834 -3.7% 12504 13545 -7.7%
    2 3 हैदराबाद HYDERABAD (GHIAL) 12082 14411 -16.2% 65163 76564 -14.9%
    5 3 हैदराबाद HYDERABAD (GHIAL) 14812 17245 -14.1% 77667 90109 -13.8%

================================================================================
Month : 2026-08
Metric: Freight
File  : Aug2k26Annex_4.pdf
 page                                                                    line
    1  3हैदराबाद HYDERABAD (GHIAL) 11640.6 8725.1 33.4% 56520.2 41546.7 36.0%
    2   3हैदराबाद HYDERABAD (GHIAL) 5848.5 6232.5 -6.2% 29719.7 30580.9 -2.8%
    5 3हैदराबाद HYDERABAD (GHIAL) 17489.1 14957.6 16.9% 86240.0 72127.6 19.6%

================================================================================
Month : 2026-08
Metric: Passengers
File  : Aug2k26Annex3.pdf
 page                                                                         line
    1       3 हैदराबाद HYDERABAD (GHIAL) 452164 464341 -2.6% 2117531 2261073 -6.3%
    2  3 हैदराबाद HYDERABAD (GHIAL) 1733770 2005921 -13.6% 9379416 10734561 -12.6%
    5 3 हैदराबाद HYDERABAD (GHIAL) 2185934 2470262 -11.5% 11496947 12995634 -11.5%

In [42]:
# ============================================================
# Bulk Extraction — RGIA Monthly Traffic Data
# ============================================================

def extract_rgia_from_file(filepath, metric_name, report_month):
    """
    Extract International, Domestic and Combined RGIA records
    from an AAI traffic report PDF.
    """

    with open(filepath, "rb") as f:
        pdf_bytes = f.read()

    pages = extract_pdf_text(pdf_bytes)

    traffic_type_by_page = {
        1: "International",
        2: "Domestic",
        5: "Combined"
    }

    rows = []

    for page_no, traffic_type in traffic_type_by_page.items():

        page_text = pages[page_no - 1]

        rgia_found = False

        for line in page_text.splitlines():

            if (
                "HYDERABAD" in line.upper()
                and "GHIAL" in line.upper()
            ):

                parsed = parse_rgya_line(line)

                if parsed is not None:

                    rows.append({
                        "report_month": report_month,
                        "metric": metric_name,
                        "traffic_type": traffic_type,
                        **parsed
                    })

                    rgia_found = True
                    break

        if not rgia_found:
            print(
                f"WARNING: RGIA row not found | "
                f"{report_month} | {metric_name} | "
                f"Page {page_no}"
            )

    return rows


# ------------------------------------------------------------
# Extract all reports
# ------------------------------------------------------------

all_rows = []

for _, row in manifest.iterrows():

    metric = row["metric"]
    report_month = row["report_month"]
    filename = row["filename"]

    metric_folder = metric.lower().replace(" ", "_")

    filepath = os.path.join(
        RAW_DIR,
        metric_folder,
        filename
    )

    extracted_rows = extract_rgia_from_file(
        filepath,
        metric,
        report_month
    )

    all_rows.extend(extracted_rows)


rgia_traffic_raw = pd.DataFrame(all_rows)

print("Extraction complete.")
print("Rows:", len(rgia_traffic_raw))
print("Columns:", len(rgia_traffic_raw.columns))

rgia_traffic_raw.head(10)

Extraction complete.
Rows: 72
Columns: 9

,report_month,metric,traffic_type,month_current,month_previous_year,month_change_pct,period_current,period_previous_year,period_change_pct
0,2026-01,Aircraft Movements,International,2895.0,2522.0,14.8,27535.0,25115.0,9.6
1,2026-01,Aircraft Movements,Domestic,13999.0,15271.0,-8.3,149557.0,141750.0,5.5
2,2026-01,Aircraft Movements,Combined,16894.0,17793.0,-5.1,177092.0,166865.0,6.1
3,2026-01,Freight,International,9311.5,7302.2,27.5,90615.5,80941.4,12.0
4,2026-01,Freight,Domestic,5596.8,5487.2,2.0,60536.5,57730.9,4.9
5,2026-01,Freight,Combined,14908.4,12789.4,16.6,151152.0,138672.3,9.0
6,2026-01,Passengers,International,523439.0,424013.0,23.4,4717724.0,3935053.0,19.9
7,2026-01,Passengers,Domestic,2129340.0,2218574.0,-4.0,21160774.0,20104882.0,5.3
8,2026-01,Passengers,Combined,2652779.0,2642587.0,0.4,25878498.0,24039935.0,7.6
9,2026-02,Aircraft Movements,International,2573.0,2429.0,5.9,30108.0,27544.0,9.3

In [43]:
# ============================================================
# Validation 1 — International + Domestic = Combined
# ============================================================

reconciliation_rows = []

for (month, metric), group in rgia_traffic_raw.groupby(
    ["report_month", "metric"]
):

    international = group.loc[
        group["traffic_type"] == "International",
        "month_current"
    ].iloc[0]

    domestic = group.loc[
        group["traffic_type"] == "Domestic",
        "month_current"
    ].iloc[0]

    combined = group.loc[
        group["traffic_type"] == "Combined",
        "month_current"
    ].iloc[0]

    calculated_combined = international + domestic

    difference = combined - calculated_combined

    reconciliation_rows.append({
        "report_month": month,
        "metric": metric,
        "international": international,
        "domestic": domestic,
        "reported_combined": combined,
        "calculated_combined": calculated_combined,
        "difference": difference
    })


reconciliation_df = pd.DataFrame(reconciliation_rows)

print("Total reconciliation checks:", len(reconciliation_df))
print(
    "Exact matches:",
    (reconciliation_df["difference"] == 0).sum()
)

print(
    "Maximum absolute difference:",
    reconciliation_df["difference"].abs().max()
)

reconciliation_df

Total reconciliation checks: 24
Exact matches: 21
Maximum absolute difference: 0.10000000000218279

,report_month,metric,international,domestic,reported_combined,calculated_combined,difference
0,2026-01,Aircraft Movements,2895.0,13999.0,16894.0,16894.0,0.000000e+00
1,2026-01,Freight,9311.5,5596.8,14908.4,14908.3,1.000000e-01
2,2026-01,Passengers,523439.0,2129340.0,2652779.0,2652779.0,0.000000e+00
3,2026-02,Aircraft Movements,2573.0,12328.0,14901.0,14901.0,0.000000e+00
4,2026-02,Freight,9992.7,5455.2,15447.9,15447.9,-1.818989e-12
5,2026-02,Passengers,429602.0,1887511.0,2317113.0,2317113.0,0.000000e+00
6,2026-03,Aircraft Movements,1954.0,13953.0,15907.0,15907.0,0.000000e+00
7,2026-03,Freight,9667.2,6172.9,15840.1,15840.1,0.000000e+00
8,2026-03,Passengers,315776.0,1972498.0,2288274.0,2288274.0,0.000000e+00
9,2026-04,Aircraft Movements,2010.0,13819.0,15829.0,15829.0,0.000000e+00
10,2026-04,Freight,10317.0,5843.6,16160.6,16160.6,0.000000e+00
11,2026-04,Passengers,340896.0,1909069.0,2249965.0,2249965.0,0.000000e+00
12,2026-05,Aircraft Movements,2391.0,14915.0,17306.0,17306.0,0.000000e+00
13,2026-05,Freight,10390.0,6159.4,16549.3,16549.4,-1.000000e-01
14,2026-05,Passengers,414359.0,2135341.0,2549700.0,2549700.0,0.000000e+00
15,2026-06,Aircraft Movements,2623.0,12733.0,15356.0,15356.0,0.000000e+00
16,2026-06,Freight,12082.1,5888.1,17970.2,17970.2,0.000000e+00
17,2026-06,Passengers,430164.0,1857680.0,2287844.0,2287844.0,0.000000e+00
18,2026-07,Aircraft Movements,2750.0,11614.0,14364.0,14364.0,0.000000e+00
19,2026-07,Freight,12090.6,5980.2,18070.8,18070.8,0.000000e+00
20,2026-07,Passengers,479948.0,1743556.0,2223504.0,2223504.0,0.000000e+00
21,2026-08,Aircraft Movements,2730.0,12082.0,14812.0,14812.0,0.000000e+00
22,2026-08,Freight,11640.6,5848.5,17489.1,17489.1,0.000000e+00
23,2026-08,Passengers,452164.0,1733770.0,2185934.0,2185934.0,0.000000e+00

In [ ]:
# ============================================================
# Reconciliation Summary
# ============================================================

reconciliation_df["abs_difference"] = (
    reconciliation_df["difference"].abs()
)

print("Differences by metric:")
print(
    reconciliation_df
    .groupby("metric")["abs_difference"]
    .agg(["max", "mean"])
)

print("\nRecords with non-zero difference:")

print(
    reconciliation_df[
        reconciliation_df["abs_difference"] > 0
    ][
        [
            "report_month",
            "metric",
            "international",
            "domestic",
            "reported_combined",
            "calculated_combined",
            "difference"
        ]
    ]
)

In [46]:
# ============================================================
# Reconciliation Summary
# ============================================================

reconciliation_df["abs_difference"] = (
    reconciliation_df["difference"].abs()
)

print("Differences by metric:")
print(
    reconciliation_df
    .groupby("metric")["abs_difference"]
    .agg(["max", "mean"])
)

print("\nRecords with non-zero difference:")

print(
    reconciliation_df[
        reconciliation_df["abs_difference"] > 0
    ][
        [
            "report_month",
            "metric",
            "international",
            "domestic",
            "reported_combined",
            "calculated_combined",
            "difference"
        ]
    ]
)

Differences by metric:
                    max   mean
metric
Aircraft Movements  0.0  0.000
Freight             0.1  0.025
Passengers          0.0  0.000

Records with non-zero difference:
   report_month   metric  international  domestic  reported_combined  \
1       2026-01  Freight         9311.5    5596.8            14908.4
4       2026-02  Freight         9992.7    5455.2            15447.9
13      2026-05  Freight        10390.0    6159.4            16549.3

    calculated_combined    difference
1               14908.3  1.000000e-01
4               15447.9 -1.818989e-12
13              16549.4 -1.000000e-01

In [45]:
# ============================================================
# Validation 2 — Independent YoY Calculation
# ============================================================

def calculate_yoy(current, previous):

    if previous == 0:
        return np.nan

    return ((current - previous) / previous) * 100


rgia_traffic_raw["calculated_month_change_pct"] = (
    rgia_traffic_raw.apply(
        lambda row: calculate_yoy(
            row["month_current"],
            row["month_previous_year"]
        ),
        axis=1
    )
)

rgia_traffic_raw["yoy_pct_difference"] = (
    rgia_traffic_raw["calculated_month_change_pct"]
    - rgia_traffic_raw["month_change_pct"]
)


print(
    "Maximum absolute YoY difference:",
    rgia_traffic_raw["yoy_pct_difference"]
    .abs()
    .max()
)

print(
    "Records within 0.05 percentage points:",
    (
        rgia_traffic_raw["yoy_pct_difference"].abs() <= 0.05
    ).sum(),
    "out of",
    len(rgia_traffic_raw)
)

print("\nLargest differences:")

print(
    rgia_traffic_raw[
        [
            "report_month",
            "metric",
            "traffic_type",
            "month_change_pct",
            "calculated_month_change_pct",
            "yoy_pct_difference"
        ]
    ]
    .sort_values(
        "yoy_pct_difference",
        key=lambda x: x.abs(),
        ascending=False
    )
    .head(10)
)

Maximum absolute YoY difference: 0.04979923124033192
Records within 0.05 percentage points: 72 out of 72

Largest differences:
   report_month              metric   traffic_type  month_change_pct  \
24      2026-03          Passengers  International             -24.8
21      2026-03             Freight  International              -8.9
50      2026-06             Freight       Combined              24.2
36      2026-05  Aircraft Movements  International              -8.9
58      2026-07             Freight       Domestic              -4.9
6       2026-01          Passengers  International              23.4
44      2026-05          Passengers       Combined              -8.6
15      2026-02          Passengers  International              14.2
2       2026-01  Aircraft Movements       Combined              -5.1
39      2026-05             Freight  International              32.9

    calculated_month_change_pct  yoy_pct_difference
24                   -24.750201            0.049799
21                    -8.850734            0.049266
50                    24.150748           -0.049252
36                    -8.948972           -0.048972
58                    -4.851156            0.048844
6                     23.448809            0.048809
44                    -8.648723           -0.048723
15                    14.151718           -0.048282
2                     -5.052549            0.047451
39                    32.852558           -0.047442

In [47]:
# ============================================================
# Create Validated Base Dataset
# ============================================================

validated_columns = [
    "report_month",
    "metric",
    "traffic_type",
    "month_current",
    "month_previous_year",
    "month_change_pct",
    "period_current",
    "period_previous_year",
    "period_change_pct"
]

rgia_traffic_validated = (
    rgia_traffic_raw[validated_columns]
    .copy()
)

# Convert report_month to proper date
rgia_traffic_validated["report_month"] = pd.to_datetime(
    rgia_traffic_validated["report_month"],
    format="%Y-%m"
)

# Sort
rgia_traffic_validated = (
    rgia_traffic_validated
    .sort_values(
        [
            "report_month",
            "metric",
            "traffic_type"
        ]
    )
    .reset_index(drop=True)
)

# Save
VALIDATED_FILE = os.path.join(
    PROCESSED_DIR,
    "rgia_traffic_monthly_2026.csv"
)

rgia_traffic_validated.to_csv(
    VALIDATED_FILE,
    index=False
)

print("Validated dataset saved successfully.")
print("File:", VALIDATED_FILE)
print("Rows:", len(rgia_traffic_validated))
print("Columns:", len(rgia_traffic_validated.columns))

rgia_traffic_validated.head(12)

Validated dataset saved successfully.
File: /content/rgia_airport_analytics/data/processed/rgia_traffic_monthly_2026.csv
Rows: 72
Columns: 9

,report_month,metric,traffic_type,month_current,month_previous_year,month_change_pct,period_current,period_previous_year,period_change_pct
0,2026-01-01,Aircraft Movements,Combined,16894.0,17793.0,-5.1,177092.0,166865.0,6.1
1,2026-01-01,Aircraft Movements,Domestic,13999.0,15271.0,-8.3,149557.0,141750.0,5.5
2,2026-01-01,Aircraft Movements,International,2895.0,2522.0,14.8,27535.0,25115.0,9.6
3,2026-01-01,Freight,Combined,14908.4,12789.4,16.6,151152.0,138672.3,9.0
4,2026-01-01,Freight,Domestic,5596.8,5487.2,2.0,60536.5,57730.9,4.9
5,2026-01-01,Freight,International,9311.5,7302.2,27.5,90615.5,80941.4,12.0
6,2026-01-01,Passengers,Combined,2652779.0,2642587.0,0.4,25878498.0,24039935.0,7.6
7,2026-01-01,Passengers,Domestic,2129340.0,2218574.0,-4.0,21160774.0,20104882.0,5.3
8,2026-01-01,Passengers,International,523439.0,424013.0,23.4,4717724.0,3935053.0,19.9
9,2026-02-01,Aircraft Movements,Combined,14901.0,16913.0,-11.9,191993.0,183778.0,4.5
10,2026-02-01,Aircraft Movements,Domestic,12328.0,14484.0,-14.9,161885.0,156234.0,3.6
11,2026-02-01,Aircraft Movements,International,2573.0,2429.0,5.9,30108.0,27544.0,9.3

In [48]:
# ============================================================
# Final Dataset Integrity Check
# ============================================================

print("Shape:", rgia_traffic_validated.shape)

print("\nMissing values:")
print(
    rgia_traffic_validated.isna().sum()
)

print("\nDuplicate rows:")
print(
    rgia_traffic_validated.duplicated().sum()
)

print("\nUnique months:")
print(
    rgia_traffic_validated["report_month"]
    .dt.strftime("%Y-%m")
    .unique()
)

print("\nUnique metrics:")
print(
    rgia_traffic_validated["metric"].unique()
)

print("\nUnique traffic types:")
print(
    rgia_traffic_validated["traffic_type"].unique()
)

Shape: (72, 9)

Missing values:
report_month            0
metric                  0
traffic_type            0
month_current           0
month_previous_year     0
month_change_pct        0
period_current          0
period_previous_year    0
period_change_pct       0
dtype: int64

Duplicate rows:
0

Unique months:
['2026-01' '2026-02' '2026-03' '2026-04' '2026-05' '2026-06' '2026-07'
 '2026-08']

Unique metrics:
['Aircraft Movements' 'Freight' 'Passengers']

Unique traffic types:
['Combined' 'Domestic' 'International']

In [49]:
# ============================================================
# Operational KPI Dataset
# ============================================================

# ------------------------------------------------------------
# Extract monthly values by metric and traffic type
# ------------------------------------------------------------

passengers = rgia_traffic_validated[
    rgia_traffic_validated["metric"] == "Passengers"
].copy()

movements = rgia_traffic_validated[
    rgia_traffic_validated["metric"] == "Aircraft Movements"
].copy()

freight = rgia_traffic_validated[
    rgia_traffic_validated["metric"] == "Freight"
].copy()


# ------------------------------------------------------------
# Keep only the values needed for KPI construction
# ------------------------------------------------------------

passenger_pivot = passengers.pivot(
    index="report_month",
    columns="traffic_type",
    values="month_current"
).reset_index()

passenger_pivot = passenger_pivot.rename(
    columns={
        "International": "international_passengers",
        "Domestic": "domestic_passengers",
        "Combined": "total_passengers"
    }
)


movement_pivot = movements.pivot(
    index="report_month",
    columns="traffic_type",
    values="month_current"
).reset_index()

movement_pivot = movement_pivot.rename(
    columns={
        "International": "international_movements",
        "Domestic": "domestic_movements",
        "Combined": "total_movements"
    }
)


freight_pivot = freight.pivot(
    index="report_month",
    columns="traffic_type",
    values="month_current"
).reset_index()

freight_pivot = freight_pivot.rename(
    columns={
        "International": "international_freight_mt",
        "Domestic": "domestic_freight_mt",
        "Combined": "total_freight_mt"
    }
)


# ------------------------------------------------------------
# Combine datasets
# ------------------------------------------------------------

rgia_monthly_kpi = (
    passenger_pivot
    .merge(
        movement_pivot,
        on="report_month",
        how="inner"
    )
    .merge(
        freight_pivot,
        on="report_month",
        how="inner"
    )
)


# ------------------------------------------------------------
# Operational KPIs
# ------------------------------------------------------------

rgia_monthly_kpi["passengers_per_aircraft_movement"] = (
    rgia_monthly_kpi["total_passengers"]
    / rgia_monthly_kpi["total_movements"]
)

rgia_monthly_kpi["freight_per_aircraft_movement_mt"] = (
    rgia_monthly_kpi["total_freight_mt"]
    / rgia_monthly_kpi["total_movements"]
)


# ------------------------------------------------------------
# Passenger mix
# ------------------------------------------------------------

rgia_monthly_kpi["domestic_passenger_share_pct"] = (
    rgia_monthly_kpi["domestic_passengers"]
    / rgia_monthly_kpi["total_passengers"]
    * 100
)

rgia_monthly_kpi["international_passenger_share_pct"] = (
    rgia_monthly_kpi["international_passengers"]
    / rgia_monthly_kpi["total_passengers"]
    * 100
)


# ------------------------------------------------------------
# Aircraft movement mix
# ------------------------------------------------------------

rgia_monthly_kpi["domestic_movement_share_pct"] = (
    rgia_monthly_kpi["domestic_movements"]
    / rgia_monthly_kpi["total_movements"]
    * 100
)

rgia_monthly_kpi["international_movement_share_pct"] = (
    rgia_monthly_kpi["international_movements"]
    / rgia_monthly_kpi["total_movements"]
    * 100
)


# ------------------------------------------------------------
# Month-over-month passenger growth
# ------------------------------------------------------------

rgia_monthly_kpi["passenger_mom_growth_pct"] = (
    rgia_monthly_kpi["total_passengers"]
    .pct_change()
    * 100
)


# ------------------------------------------------------------
# Month-over-month movement growth
# ------------------------------------------------------------

rgia_monthly_kpi["movement_mom_growth_pct"] = (
    rgia_monthly_kpi["total_movements"]
    .pct_change()
    * 100
)


# ------------------------------------------------------------
# Month-over-month freight growth
# ------------------------------------------------------------

rgia_monthly_kpi["freight_mom_growth_pct"] = (
    rgia_monthly_kpi["total_freight_mt"]
    .pct_change()
    * 100
)


# ------------------------------------------------------------
# Final ordering
# ------------------------------------------------------------

rgia_monthly_kpi = (
    rgia_monthly_kpi
    .sort_values("report_month")
    .reset_index(drop=True)
)


print("KPI dataset shape:", rgia_monthly_kpi.shape)

rgia_monthly_kpi

KPI dataset shape: (8, 19)

traffic_type,report_month,total_passengers,domestic_passengers,international_passengers,total_movements,domestic_movements,international_movements,total_freight_mt,domestic_freight_mt,international_freight_mt,passengers_per_aircraft_movement,freight_per_aircraft_movement_mt,domestic_passenger_share_pct,international_passenger_share_pct,domestic_movement_share_pct,international_movement_share_pct,passenger_mom_growth_pct,movement_mom_growth_pct,freight_mom_growth_pct
0,2026-01-01,2652779.0,2129340.0,523439.0,16894.0,13999.0,2895.0,14908.4,5596.8,9311.5,157.024920,0.882467,80.268277,19.731723,82.863739,17.136261,NaN,NaN,NaN
1,2026-02-01,2317113.0,1887511.0,429602.0,14901.0,12328.0,2573.0,15447.9,5455.2,9992.7,155.500503,1.036702,81.459601,18.540399,82.732703,17.267297,-12.653372,-11.797088,3.618765
2,2026-03-01,2288274.0,1972498.0,315776.0,15907.0,13953.0,1954.0,15840.1,6172.9,9667.2,143.853272,0.995794,86.200254,13.799746,87.716100,12.283900,-1.244609,6.751225,2.538856
3,2026-04-01,2249965.0,1909069.0,340896.0,15829.0,13819.0,2010.0,16160.6,5843.6,10317.0,142.141955,1.020949,84.848831,15.151169,87.301788,12.698212,-1.674144,-0.490350,2.023346
4,2026-05-01,2549700.0,2135341.0,414359.0,17306.0,14915.0,2391.0,16549.3,6159.4,10390.0,147.330406,0.956275,83.748716,16.251284,86.183982,13.816018,13.321763,9.330975,2.405232
5,2026-06-01,2287844.0,1857680.0,430164.0,15356.0,12733.0,2623.0,17970.2,5888.1,12082.1,148.986976,1.170240,81.197844,18.802156,82.918729,17.081271,-10.270071,-11.267768,8.585862
6,2026-07-01,2223504.0,1743556.0,479948.0,14364.0,11614.0,2750.0,18070.8,5980.2,12090.6,154.796992,1.258062,78.414790,21.585210,80.854915,19.145085,-2.812255,-6.460016,0.559816
7,2026-08-01,2185934.0,1733770.0,452164.0,14812.0,12082.0,2730.0,17489.1,5848.5,11640.6,147.578585,1.180739,79.314838,20.685162,81.568998,18.431002,-1.689675,3.118908,-3.219005

In [50]:

# Final KPI Dataset — Integrity Check & Save

# Remove accidental index name if present
rgia_monthly_kpi.index.name = None

# Make sure there is no unwanted traffic_type column
print("Columns:")
print(rgia_monthly_kpi.columns.tolist())

print("\nShape:", rgia_monthly_kpi.shape)

print("\nMissing values:")
print(rgia_monthly_kpi.isna().sum())

print("\nDuplicate rows:")
print(rgia_monthly_kpi.duplicated().sum())

Columns:
['report_month', 'total_passengers', 'domestic_passengers', 'international_passengers', 'total_movements', 'domestic_movements', 'international_movements', 'total_freight_mt', 'domestic_freight_mt', 'international_freight_mt', 'passengers_per_aircraft_movement', 'freight_per_aircraft_movement_mt', 'domestic_passenger_share_pct', 'international_passenger_share_pct', 'domestic_movement_share_pct', 'international_movement_share_pct', 'passenger_mom_growth_pct', 'movement_mom_growth_pct', 'freight_mom_growth_pct']

Shape: (8, 19)

Missing values:
traffic_type
report_month                         0
total_passengers                     0
domestic_passengers                  0
international_passengers             0
total_movements                      0
domestic_movements                   0
international_movements              0
total_freight_mt                     0
domestic_freight_mt                  0
international_freight_mt             0
passengers_per_aircraft_movement     0
freight_per_aircraft_movement_mt     0
domestic_passenger_share_pct         0
international_passenger_share_pct    0
domestic_movement_share_pct          0
international_movement_share_pct     0
passenger_mom_growth_pct             1
movement_mom_growth_pct              1
freight_mom_growth_pct               1
dtype: int64

Duplicate rows:
0

In [51]:

# Save Operational KPI Dataset

KPI_FILE = os.path.join(
    PROCESSED_DIR,
    "rgia_monthly_operational_kpis_2026.csv"
)

rgia_monthly_kpi.to_csv(
    KPI_FILE,
    index=False
)

print("KPI dataset saved successfully.")
print("File:", KPI_FILE)

KPI dataset saved successfully.
File: /content/rgia_airport_analytics/data/processed/rgia_monthly_operational_kpis_2026.csv

In [52]:
from google.colab import files

files.download(
    "/content/rgia_airport_analytics/data/processed/rgia_traffic_monthly_2026.csv"
)

files.download(
    "/content/rgia_airport_analytics/data/processed/rgia_monthly_operational_kpis_2026.csv"
)